
! =======================================================
! | MAESTRA: March 2009 Version                            |
! | For more information see www.bio.mq.edu.au/maestra  |
! | Based on Wang & Jarvis (1990) Ag For Met 51:257-280 |
! =======================================================

!------------------------------------------------------------------------
! This file contains the main program.
! It also contains subroutines to zero arrays (ZEROHR, ZEROHIST, ZEROD)
! and to sum arrays (SUMHR, SUMDAILY).
! All other code is contained in the additional files: -
!   radn.for - calculation of radiation interception
!   physiol.for - physiology subroutines
!   getmet.for - read in met data
!   inout.for - handle input & output data
!   utils.for - utility subroutines.
!------------------------------------------------------------------------

      PROGRAM MAESTRA

!-----------------------------------------------------------------------
!     An array model to predict radiation regime inside a plant
!  community. Especially suited to forest stands where crown shape
!  is described using a cone or elipsoid.
!     This program consists of three main parts, i.e.
!  1: radiation in the atmosphere , daylength and the position of
!     the sun at different hours of the day;
!  2: plant canopy architecture.3-D leaf area distribution and random
!     and nonrandom leaf area dispersion inside crown has been incorporated
!     into the radiation model with the spherical leaf angular distribution
!     assumption;radiation penetration and scattering processes.
!     A multi-scattering model proposed by John Norman is used.
!  3: both photosynthesis and transpiration are calculated using the
!     combined gs-A-E-H model.
!------------------------------------------------------------------------

! TO DO : STITLE and PTITLE are not read, see "READ (USTR, 990) STITLE" in inout.for.
! - ****include MAESTEST within Maestra (to run maestra at set grid points)****
! - DATES should not be necessary in BBMGS when NDATES=1; but it is......

      USE maestcom
      IMPLICIT NONE
      
! Array declarations.
! List of trees for which to do calculations
      INTEGER ITARGETS(MAXT)
      INTEGER ISPECIES(MAXT),ISPECIEST(MAXT),ISPECIESTUS(MAXT)

! Tree positions and dimensions - all trees, all dates
      REAL DXT1(MAXT),DYT1(MAXT),DZT1(MAXT)
      REAL RXTABLE1(MAXDATE,MAXT),RYTABLE1(MAXDATE,MAXT)
      REAL RZTABLE1(MAXDATE,MAXT),ZBCTABLE1(MAXDATE,MAXT)
      REAL FOLTABLE1(MAXDATE,MAXT),DIAMTABLE1(MAXDATE,MAXT)
! Tree positions and dimensions - sorted trees, all dates
      REAL RXTABLE(MAXDATE,MAXT),RYTABLE(MAXDATE,MAXT)
      REAL RZTABLE(MAXDATE,MAXT),ZBCTABLE(MAXDATE,MAXT)
      REAL FOLTABLE(MAXDATE,MAXT),TOTLAITABLE(MAXDATE)  !!!!!!
      REAL DIAMTABLE(MAXDATE,MAXT)
! Dates for tree dimensions
      INTEGER DATESX(MAXDATE),DATESY(MAXDATE),DATESZ(MAXDATE)
      INTEGER DATEST(MAXDATE),DATESLA(MAXDATE),DATESD(MAXDATE)
! Tree dimensions on simulation date (by interpolation)
      REAL DXT(MAXT),DYT(MAXT),DZT(MAXT)
      REAL RX(MAXT),RY(MAXT),RZ(MAXT),ZBC(MAXT)
      REAL FOLT(MAXT),DIAM(MAXT)
      REAL CANOPYDIMS(6)
! Positions of grid points, associated volume & leaf area, etc
      REAL XL(MAXP),YL(MAXP),ZL(MAXP),VL(MAXP),DLT(MAXP),DLI(MAXC,MAXP)
      INTEGER LGP(MAXP),LAYER(MAXP),MLAYER(MAXP), PPLAY
      REAL FOLLAY(MAXLAY),WINDLAY(MAXLAY)
     
! Understorey arrays.
      REAL XLU(MAXP),YLU(MAXP),ZLU(MAXP) ! Understorey points.
      REAL TUUS(MAXP),TDUS(MAXP),RELDFUS(MAXP)  ! Understorey.
      INTEGER LAYERUS(MAXP),MLAYERUS(MAXP) ! not implemented yet
      REAL UIBEAM(MAXHRS,MAXP),UIDIFF(MAXHRS,MAXP)
      REAL PARUS(MAXHRS,MAXP),APARUS(MAXHRS,MAXP)
      REAL PSUS(MAXHRS,MAXP),ETUS(MAXHRS,MAXP)
      REAL PARUNDER(MAXHRS,MAXP),USLAITAB(MAXDATE,MAXT)
      REAL USLAI(MAXP),DIAMUS(MAXDATE,MAXT)
      REAL HTUS(MAXDATE,MAXT),FOLNUS(MAXDATE,MAXT)
      INTEGER DATESFU(MAXDATE),DATESDU(MAXDATE)
      INTEGER DATESHU(MAXDATE),DATESNU(MAXDATE),OUTFORMATUS
      REAL JMAXN25,JMAX25M
      REAL FUS(MAXP),DUS(MAXP),AREAUS(MAXP),FN0US(MAXP)
      REAL DXTUS(MAXT),DYTUS(MAXT),DZTUS(MAXT)
      REAL RXTABLEUS(MAXDATE,MAXT),RYTABLEUS(MAXDATE,MAXT)
      REAL RZTABLEUS(MAXDATE,MAXT)
      REAL FOLTABLEUS(MAXDATE,MAXT),ZBCTABLEUS(MAXDATE,MAXT)
      REAL DIAMTABLEUS(MAXDATE,MAXT)
      REAL RXUS(MAXT),RYUS(MAXT),RZUS(MAXT)
      REAL ZBCUS(MAXT),FOLTUS(MAXT),PARUSMEAN(MAXHRS)
      REAL PARUSSD(MAXHRS),THRABUS(MAXHRS),FCO2US(MAXHRS),FH2OUS(MAXHRS)
      REAL XUS0,YUS0

! Test point arrays
      REAL XLP(MAXP),YLP(MAXP),ZLP(MAXP)
      REAL TUP(MAXP),TDP(MAXP),RELDFP(MAXP)
      INTEGER LAYERP(MAXP),MLAYERP(MAXP)
      REAL DXTP(MAXT),DYTP(MAXT),DZTP(MAXT)
      REAL RXTABLEP(MAXDATE,MAXT),RYTABLEP(MAXDATE,MAXT)
      REAL RZTABLEP(MAXDATE,MAXT)
      REAL FOLTABLEP(MAXDATE,MAXT),ZBCTABLEP(MAXDATE,MAXT)
      REAL DIAMTABLEP(MAXDATE,MAXT)
      REAL RXP(MAXT),RYP(MAXT),RZP(MAXT)
      REAL ZBCP(MAXT),FOLTP(MAXT)
      INTEGER ISPECIESP(MAXT),ISPECIESTP(MAXT)
      INTEGER JSHAPETP(MAXT),JLEAFTP(MAXT),NOAGECTP(MAXT)
      REAL SHAPETP(MAXT),DEXTTP(MAXT,MAXANG),BPTTP(8,MAXC,MAXT)
      REAL PROPPTP(MAXC,MAXT),PROPCTP(MAXC,MAXT)
      
! Met data
      INTEGER METCOLS(MAXMET),SOILDATA
      REAL WINDAH(MAXHRS),TSOIL(MAXHRS),TAIR(MAXHRS),RADABV(MAXHRS,3)
      REAL FBEAM(MAXHRS,3),RH(MAXHRS),VPD(MAXHRS),VMFD(MAXHRS)
      REAL CA(MAXHRS),PRESS(MAXHRS),PPT(MAXHRS),SOILMOIST(MAXHRS)
      REAL DELTAT(12)
      
! Physiology inputs by layer
      REAL ABSRP(MAXLAY,3),ARHO(MAXLAY,3),ATAU(MAXLAY,3)
      REAL RHOSOL(3)
      REAL JMAXTABLE(maxdate,MAXLAY,MAXC)
      REAL VCMAXTABLE(maxdate,MAXLAY,MAXC)
      REAL RDTABLE(MAXDATE,MAXLAY,MAXC)
      REAL SLATABLE(MAXDATE,MAXLAY,MAXC)
      REAL AJQTABLE(MAXDATE,MAXLAY,MAXC)
      REAL Q10FTABLE(MAXDATE), Q10WTABLE(MAXDATE)
      INTEGER DATESFQ(MAXDATE), DATESWQ(MAXDATE)
      INTEGER DATESJ(MAXDATE), DATESV(MAXDATE)
      INTEGER DATESRD(MAXDATE), DATESSLA(MAXDATE)
      INTEGER DATESA(MAXDATE)
      REAL JMAX25(MAXLAY,MAXC),VCMAX25(MAXLAY,MAXC)
      REAL RD0(MAXLAY,MAXC),SLA(MAXLAY,MAXC),AJQ(MAXLAY,MAXC)
      
! Structural data inputs
      REAL BPT(8,MAXC),PROPP(MAXC),PROPC(MAXC)
      REAL ALPHA(MAXANG),FALPHA(MAXANG)
      
! Intermediate calculations
      REAL DIFZEN(MAXANG),DEXT(MAXANG),BEXTANG(MAXANG)
      REAL DEXTP(MAXANG)
      REAL ZEN(MAXHRS),AZ(MAXHRS)
      REAL TU(MAXP),TD(MAXP),RELDF(MAXP)
      REAL DIFDN(MAXP,3),DIFUP(MAXP,3),SCLOST(MAXP,3)
      REAL BFLUX(MAXP,3),DFLUX(MAXP,3),SCATFX(MAXP,3)
      
! Outputs for each tree
      REAL THRAB(MAXHRS,3),TDYAB(3),TCAN(MAXHRS)
      REAL FCO2(MAXHRS),FH2O(MAXHRS)
      REAL GSCAN(MAXHRS),FHEAT(MAXHRS),FH2OCAN(MAXHRS)
      REAL FRESPF(MAXHRS),FRESPW(MAXHRS),FRESPB(MAXHRS)
      REAL FRESPFR(MAXHRS),FRESPCR(MAXHRS)
      REAL DECOUPL(MAXHRS)   ! RAD, MAY 2009.
      REAL PPAR(MAXLAY,MAXHRS),PPS(MAXLAY,MAXHRS),PTRANSP(MAXLAY,MAXHRS)
      
! Titles of input files
      CHARACTER*80 CTITLE,TTITLE,PTITLE,STITLE,MTITLE,VTITLE
      CHARACTER PTITLES(MAXSP)*60
      CHARACTER STITLES(MAXSP)*60
      
! Multispecies.
      CHARACTER SPECIESNAMES(MAXSP)*30
      CHARACTER PHYFILES(MAXSP)*30
      CHARACTER STRFILES(MAXSP)*30      

! STR arrays, multi-species versions.
      REAL ALPHASPEC(MAXANG,MAXSP),FALPHASPEC(MAXANG,MAXSP)
      REAL BPTSPEC(8,MAXC,MAXSP),BPTT(8,MAXC,MAXT)
      REAL BPTTUS(8,MAXC,MAXT)
      REAL SHAPESPEC(MAXSP),EXTWINDSPEC(MAXSP)
      REAL RANDOMSPEC(MAXSP),COEFFTSPEC(MAXSP)
      REAL EXPONTSPEC(MAXSP),WINTERCSPEC(MAXSP)
      REAL BCOEFFTSPEC(MAXSP),BEXPONTSPEC(MAXSP)
      REAL BINTERCSPEC(MAXSP),DEXTSPEC(MAXSP,MAXANG)
      REAL DEXTT(MAXT,MAXANG),DEXTTUS(MAXT,MAXANG)
      REAL BEXTSPEC(MAXSP),BEXTANGSPEC(MAXSP,MAXANG)
      REAL BEXTANGT(MAXP,MAXANG),BEXTANGTUS(MAXP,MAXANG)
      REAL BEXTANGTP(MAXP,MAXANG)
      REAL BEXTT(MAXT),BEXTTUS(MAXT),BEXTTP(MAXT)
      REAL RCOEFFTSPEC(MAXSP),REXPONTSPEC(MAXSP)
      REAL RINTERCSPEC(MAXSP),FRFRACSPEC(MAXSP)
      INTEGER NOAGECSPEC(MAXSP),NOAGECT(MAXT),NOAGECTUS(MAXT)
      INTEGER JLEAFSPEC(MAXSP),JLEAFT(MAXT),JLEAFTUS(MAXT)
      INTEGER JSHAPESPEC(MAXSP), NALPHASPEC(MAXSP)
      INTEGER JSHAPET(MAXT),JSHAPETUS(MAXT)
      REAL SHAPET(MAXT),SHAPETUS(MAXT)

! PHY arrays, multi-species versions.
      REAL ABSRPSPEC(MAXLAY,3,MAXSP),ARHOSPEC(MAXLAY,3,MAXSP)
      REAL ATAUSPEC(MAXLAY,3,MAXSP),RHOSOLSPEC(3,MAXSP)
      REAL PROPPSPEC(MAXC,MAXSP),PROPCSPEC(MAXC,MAXSP)
      REAL PROPPT(MAXC,MAXT),PROPCT(MAXC,MAXT)
      REAL PROPPTUS(MAXC,MAXT),PROPCTUS(MAXC,MAXT)
      REAL LEAFNSPEC(MAXDATE,MAXLAY,MAXC,MAXSP)
      REAL JMAXTABLESPEC(MAXDATE,MAXLAY,MAXC,MAXSP)
      REAL VCMAXTABLESPEC(MAXDATE,MAXLAY,MAXC,MAXSP)
      REAL RDTABLESPEC(MAXDATE,MAXLAY,MAXC,MAXSP)
      REAL SLATABLESPEC(MAXDATE,MAXLAY,MAXC,MAXSP)
      REAL AJQTABLESPEC(MAXDATE,MAXLAY,MAXC,MAXSP)
      REAL Q10FTABLESPEC(MAXDATE,MAXSP),Q10WTABLESPEC(MAXDATE,MAXSP)
      INTEGER DATESNSPEC(MAXDATE,MAXSP),DATESJSPEC(MAXDATE,MAXSP)
      INTEGER DATESVSPEC(MAXDATE,MAXSP),DATESRDSPEC(MAXDATE,MAXSP)
      INTEGER DATESSLASPEC(MAXDATE,MAXSP),DATESASPEC(MAXDATE,MAXSP)
      INTEGER DATESFQSPEC(MAXDATE,MAXSP),DATESWQSPEC(MAXDATE,MAXSP)
      INTEGER NOAGEPSPEC(MAXSP),NSIDESSPEC(MAXSP)
      REAL GSREFSPEC(MAXSP), GSMINSPEC(MAXSP), PAR0SPEC(MAXSP)
      REAL D0SPEC(MAXSP), VK1SPEC(MAXSP), VK2SPEC(MAXSP)
      REAL VPD1SPEC(MAXSP), VPD2SPEC(MAXSP), VMFD0SPEC(MAXSP) 
      REAL GSJASPEC(MAXSP), GSJBSPEC(MAXSP), T0SPEC(MAXSP)
      REAL TREFSPEC(MAXSP), TMAXSPEC(MAXSP), SMD1SPEC(MAXSP)
      REAL SMD2SPEC(MAXSP), WC1SPEC(MAXSP), WC2SPEC(MAXSP)
      REAL SWPEXPSPEC(MAXSP), G0SPEC(MAXSP), D0LSPEC(MAXSP)
      REAL GAMMASPEC(MAXSP), G1SPEC(MAXSP), GKSPEC(MAXSP)
      REAL WLEAFSPEC(MAXSP)
      INTEGER NOJDATESSPEC(MAXSP),NOVDATESSPEC(MAXSP)
      INTEGER NOADATESSPEC(MAXSP),NOSLADATESSPEC(MAXSP)
      INTEGER NONDATESSPEC(MAXSP),NORDATESSPEC(MAXSP)
      INTEGER NOWQDATESSPEC(MAXSP),NOFQDATESSPEC(MAXSP)
      INTEGER IECOSPEC(MAXSP)
      REAL EAVJSPEC(MAXSP), EDVJSPEC(MAXSP)
      REAL DELSJSPEC(MAXSP), EAVCSPEC(MAXSP)
      REAL EDVCSPEC(MAXSP), DELSCSPEC(MAXSP), TVJUPSPEC(MAXSP)
      REAL TVJDNSPEC(MAXSP), THETASPEC(MAXSP)
      REAL RTEMPSPEC(MAXSP), DAYRESPSPEC(MAXSP), EFFYRFSPEC(MAXSP)
      REAL TBELOWSPEC(MAXSP),EFFYRWSPEC(MAXSP),RMWSPEC(MAXSP)
      REAL RTEMPWSPEC(MAXSP),COLLASPEC(MAXSP),COLLKSPEC(MAXSP)
      REAL STEMSDWSPEC(MAXSP),RMWAREASPEC(MAXSP),STEMFORMSPEC(MAXSP)
      REAL Q10RSPEC(MAXSP),RTEMPRSPEC(MAXSP),Q10BSPEC(MAXSP)
      REAL RTEMPBSPEC(MAXSP),RMCRSPEC(MAXSP),RMFRSPEC(MAXSP)
      REAL RMBSPEC(MAXSP)
      real tmp(maxang)
      
! Temporary arrays for sunlit/shaded rates (for MAESTEST)
      REAL GSCTEST(MAXP,2),ALEAFTEST(MAXP,2)
      REAL RDTEST(MAXP,2),ETTEST(MAXP,2)

! Outputs for each point (MAESHR)
      REAL GSCHR(MAXP,2),ALEAFHR(MAXP,2),ETHR(MAXP,2)
      REAL HFXHR(MAXP,2),RNETHR(MAXP,2),SUNLAHR(MAXP),GBHHR(MAXP,2)
      REAL RDHR(MAXP,2),TLEAFHR(MAXP,2)

! Outputs for PAR histogram
      REAL HISTO(MAXHISTO)

! Other, non-arrays.
      REAL ABSRPU, AJQU, ALAT, ALEAF, ANIR, APAR, APP, AREA, ATHR
      REAL AX, AY, BALPHA, BLAMBDA, BBINC, BBIOM, BCOEFFT, BEAMP, BEAR
      REAL BEXPONT, BEXT, BEXTUS, BINSIZE, BINTERC, BMULT
      REAL CAK, CANOPY_STORE, CICARAT, CO2INC, COEFFT, COLLA, COLLK
      REAL D0, D0L, DAYRESP, DAYL, DEC, DELSC, DELSCU, DELSJ, DELSJU, DISCHARGETOT
      REAL DIFSKY, DLAI, DMULT2, DRAINSTORE, DRYTHICK, DT1, DT2!, DRYTHICHMIN
      REAL DRYTHICKMIN, DT3, DT4, EAVC, EAVCU, EAVJU, EDVC, EAVJ, EDVJ, DVJU, EDVCU
      REAL EFFY, EFFYRF, EDVJU, EMAXLEAF, EFFYRW, EQNTIM, ESOIL, ET, ETEST
      REAL ETMEASTOT, ETMM, ETMM2, ETMMTOT, ETUSMM, EVAPSTORE, EXPAN, EXPDIF, EXPINF, EXPONT
      REAL EXPTIME, EXTKUS, EXTWIND, FAREA, FBEAMOTC, FBINC, FBIOM, FRFRAC, FSOIL, FTSOIL1, FSOILMEAN
      REAL G0, G1, GAMMA, GAMSOIL, GBH, GRDAREAI, GSBG0U, GSBG1U, FSOIL1, GSC, GSIPT, GSJA, GSJB
      REAL GSREF, HFX, GSMIN,RD0US,SLAUS
      INTEGER I, IAGE, ICC, IDAY, IECO, IECOU, IEND, IFLUSH, IHOUR, IOTC
      INTEGER IPROG, IPROGUS, IPT, IPTUS, ISIMUS, ISPEC, ISTART, ISUNLIT, ITAR, ITERMAX, ITREE, IUSTFILE
      INTEGER IWATFILE, IWAVE, IWHICH, JLEAF, JSHAPE, KEEPWET, MASPDATE, MFLAG, MODELGS, MODELJM
      INTEGER MODELRD, MODELRW, MODELSS, MOSS, MOVEWINDOW, MSTART, NALPHA, NAZ, NEWCANOPY
      INTEGER NEWTUTD, NOADTES, NOAGEC, NOADATES, NOAGEP, NOALLTREES, NODDATES, NOFQDATES, NOFUDATES
      INTEGER NOGSDATES, NOHUDATES, NOJDATES, NOLADATES, NOLAY, NOMETCOLS, NONUDATES, NORDATES
      INTEGER NOSLADATES, NOTARGETS, NOTDATES, NOTREES, NOUSPOINTS, NOVDATES, NOWQDATES, NOXDATES
      INTEGER NOYDATES, NOZDATES, NSIDES, NSUMMEDW, NTAIRADD, NUMPNT, NZEN, NSTEP
      INTEGER NOTREESTEST,NOTREESUS
      REAL OUTFLOW, OVERFLOW, PAR, PAR0, PAROTC, PLANTK, PPTDAY, PPTTOT, PRESSK, PREVTSOIL, PSIL
      REAL Q10B, Q10R, Q10W, Q10F, QC, QCTOT, QE, QETOT, QH, QHTOT, QN, QNTOT
      REAL RADINTERC, RADINTERC1, RADINTERC2, RADINTERC3, RADINTERCTOT, RANDOM, RBINC, RBINOM
      REAL RBIOM, RCOEFFT, RD, RD0ACC, RDK, RDT, RESPF, REXPONT, RGLOBABV, RGLOBABV12
      REAL RGLOBUND, RINTERC, RMB, RMCR, RMFR, RMW, RMWAREA, RNET, ROOTRESFRAC, ROOTXSECAREA
      REAL RTEMP, RTEMPB, RTEMPR, RUNOFF, RUTTERB, RUTTERD, SCLOSTTOT, SHADEHT, SHAPE, SMD1, SMD2
      REAL SOILDEPTH, SOILEVAP, SOILEVAPTOT, SOILMOISTURE, SOILTK, SOMULT, STEMFORM
      REAL STEMSDW, STOCKING, SUNLA, SUNSET, RTEMPW, TMAX, TMOVE
      REAL SURFACE_WATERMM, SWMAX, SWMIN
      REAL SWPEXP, T0, THETAM, THROUGHFALL, TINC, TLEAF, TOTC, TOTESTEVAPMM
      REAL TBELOW, TDIFF, TFALLTOT, THETA, TOTRESPRG, TOTRESPBG

      REAL WINDOTC,XSLOPE,YSLOPE,X0,Y0,XMAX,YMAX,ZHT,Z0HT,ZPD,TORTPAR,TTIMD
      REAL TVJUPU,TVJDNU,VCMAXN25,UNMIN,VCMAX25M,WSOIL,WSOILROOT,WSOILMEAN
      REAL WSOILROOTMEAN,TOTTMP,TOTLAI,WINTERC,TVJUP,TVJDN,VK1,VK2,VPD1,VPD2
      REAL VMFD0,TREF,WC1,WC2,WLEAF,WBIOM,WBINC,WEIGHTEDSWP,TSCAT
      REAL FRACAPAR,VIEWFACTOR,TOTRESPWG,TOTRESPFRG,TOTRESPCRG
      REAL TOTRESPFG
    
      INTEGER IODAILY,IOHRLY,IOTUTD,IOHIST,IORESP,IPOINTS,ISUNLA,NSPECIES,NUMTESTPNT
      INTEGER IPROGCUR,IPTEST,IOFORMAT
      REAL GK,DLAIP,EXPDIFP,TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPB,TOTRESPCR
      REAL TOTRESPFR,TOTH2O,TOTHFX,SUNLAP,BEXTP,TBEAM,TTOT,DECOUP,SUNLAPOT
      REAL TOTH2OCAN
      REAL, EXTERNAL :: CALCRMW,ETCAN,RESP,GRESP,AVERAGEVAL

! Set program flag
      IPROG = INORMAL
      IPROGUS = ITEST
      VTITLE = 'MAESTRA: Version March 2009'
      
      OPEN(99, FILE='tmp.dat', STATUS='UNKNOWN')

! Ask which hour number
! MAESHR
!      WRITE (*,*) 'ENTER HOUR NUMBER (1 - ',KHRS,'): '
!      READ (*,*) IHRNO

! Open input files
      CALL OPENINPUTF(IODAILY,IOHRLY,IOTUTD,IOHIST,IORESP, &
       CTITLE,TTITLE,PTITLE,STITLE, &
       IPOINTS,ISUNLA,ISIMUS)

! Open file for points output
! MAESHR
!      OPEN (UPT, FILE = 'Ptflx.dat', STATUS='UNKNOWN')

! Get input from control file
      CALL INPUTCON( &
       ISTART, IEND, NSTEP, &
       NUMPNT, NOLAY, PPLAY, NZEN, DIFZEN, NAZ, &
       MODELGS, MODELJM, MODELRD, MODELSS, MODELRW, ITERMAX, &
       IOHIST, BINSIZE, &
       ICC, CO2INC, TINC, &
       IOTC, TOTC, WINDOTC, PAROTC, FBEAMOTC, &
       NSPECIES, SPECIESNAMES, PHYFILES, STRFILES)
       
! Get input from canopy structure file
      CALL INPUTSTR( &
       NSPECIES,STRFILES, &
       JLEAFSPEC,BPTSPEC,RANDOMSPEC,NOAGECSPEC, &
       JSHAPESPEC,SHAPESPEC,EXTWINDSPEC, &
       NALPHASPEC,ALPHASPEC,FALPHASPEC, &
       COEFFTSPEC,EXPONTSPEC,WINTERCSPEC, &
       BCOEFFTSPEC,BEXPONTSPEC,BINTERCSPEC, &
       RCOEFFTSPEC,REXPONTSPEC,RINTERCSPEC,FRFRACSPEC, &
       STITLES)

! Get input from physiology file
      CALL INPUTPHY( &
       NSPECIES,PHYFILES,MODELJM,MODELRD,MODELGS,MODELRW, &
       NOLAY,NOAGECSPEC,NOAGEPSPEC,PROPCSPEC,PROPPSPEC, &
       ABSRPSPEC,ARHOSPEC,ATAUSPEC,RHOSOLSPEC, &
       JMAXTABLESPEC,DATESJSPEC,NOJDATESSPEC,IECOSPEC,EAVJSPEC, &
       EDVJSPEC,DELSJSPEC,THETASPEC, &
       VCMAXTABLESPEC,DATESVSPEC,NOVDATESSPEC,EAVCSPEC, &
       EDVCSPEC,DELSCSPEC,TVJUPSPEC,TVJDNSPEC, &
       SLATABLESPEC,DATESSLASPEC,NOSLADATESSPEC,NOADATESSPEC, &
       DATESASPEC,AJQTABLESPEC,RDTABLESPEC, &
       DATESRDSPEC,NORDATESSPEC,RTEMPSPEC,DAYRESPSPEC,TBELOWSPEC, &
       EFFYRWSPEC,RMWSPEC,RTEMPWSPEC,COLLASPEC,COLLKSPEC, &
       STEMSDWSPEC,RMWAREASPEC,STEMFORMSPEC, &
       NOFQDATESSPEC,DATESFQSPEC,Q10FTABLESPEC,NOWQDATESSPEC, &
       DATESWQSPEC,Q10WTABLESPEC, &
       RMFRSPEC,RMCRSPEC,Q10RSPEC,RTEMPRSPEC,EFFYRFSPEC, &
       RMBSPEC,Q10BSPEC,RTEMPBSPEC, &
       GSREFSPEC,GSMINSPEC,PAR0SPEC,D0SPEC,VK1SPEC,VK2SPEC,VPD1SPEC, &
       VPD2SPEC,VMFD0SPEC,GSJASPEC,GSJBSPEC,T0SPEC,TREFSPEC, &
       TMAXSPEC,SMD1SPEC,SMD2SPEC,WC1SPEC, WC2SPEC,SWPEXPSPEC, &
       G0SPEC,D0LSPEC,GAMMASPEC,G1SPEC,GKSPEC,WLEAFSPEC,NSIDESSPEC, &
       PTITLES)
     

! Get input from trees file
      CALL INPUTTREE( &
       XSLOPE,YSLOPE,BEAR,X0,Y0,XMAX,YMAX,STOCKING, &
       ZHT,Z0HT,ZPD, &
       NOALLTREES,NOTREES,NOTARGETS,ITARGETS,SHADEHT, &
       NOXDATES,NOYDATES,NOZDATES,NOTDATES,NOLADATES,NODDATES, &
       DATESX,DATESY,DATESZ,DATEST,DATESLA,DATESD, &
       DXT1,DYT1,DZT1,RXTABLE1,RYTABLE1,RZTABLE1,ZBCTABLE1, &
       FOLTABLE1,TOTLAITABLE,DIAMTABLE1, &
       IFLUSH,DT1,DT2,DT3,DT4,EXPTIME,APP,EXPAN, &
       NSPECIES,ISPECIES)

! Open met data file (must be done after ISTART & IEND read)
      CALL OPENMETF(ISTART,IEND,CAK,PRESSK,SWMIN,SWMAX, &
       DIFSKY,ALAT,TTIMD,DELTAT, &
       MFLAG,METCOLS,NOMETCOLS,MTITLE,MSTART)

! Open output files
      CALL OPENOUTPUTF(IODAILY,IOHRLY,IOHIST,IORESP, &
       ISIMUS,ISUNLA,CTITLE,TTITLE,PTITLES,STITLES,MTITLE,VTITLE, &
       NSPECIES,SPECIESNAMES)

! Read understorey input files.
    IF(ISIMUS.EQ.1)THEN
     CALL INPUTUSSTR(NOUSPOINTS,XUS0,YUS0,GRDAREAI,XLU,YLU,ZLU, &
       USLAITAB,NOFUDATES,DATESFU, &
       HTUS,NOHUDATES,DATESHU, &
       FOLNUS,NONUDATES,DATESNU,EXTKUS,OUTFORMATUS)

     CALL INPUTUSPHY(JMAXN25,IECOU,EAVJU,EDVJU,DELSJU,TVJUPU,TVJDNU, &
       VCMAXN25,EAVCU,EDVCU,DELSCU,UNMIN, &
       AJQU,ABSRPU,GSBG0U,GSBG1U,CICARAT,RD0US,RDK,RDT,SLAUS,EFFY, &
       MOSS,JMAX25M,VCMAX25M,THETAM)
    ENDIF


! Read MAESTEST input file.
! Open files and read information about points
      IF(IPOINTS .EQ. 1)THEN
      CALL GETPOINTSF(NUMTESTPNT,XLP,YLP,ZLP,X0,Y0,XMAX,YMAX, &
         CTITLE,TTITLE,MTITLE,STITLE,VTITLE)
      ENDIF
      
! Do calculations which are not day-dependent
! Modified for multi-species option (RAD, March 2009).
      DO I=1,NSPECIES
        CALL EXDIFF(NALPHASPEC(I),ALPHASPEC(1:MAXANG,I), &
           FALPHASPEC(1:MAXANG,I), &
           NZEN,DIFZEN,RANDOMSPEC(I),DEXTSPEC(I,1:MAXANG))
      ENDDO


!**********************************************************************
! Loop over all chosen trees within subplot
      DO 50 ITAR = 1,NOTARGETS

      ITREE = ITARGETS(ITAR)
      ISPEC = ISPECIES(ITREE)

! MAESHR     
!      WRITE (*,106) ITREE
!106   FORMAT ('  TREE:',I5)


! Take first specified target tree only.
! MAESHR
!      ITREE = ITARGETS(1)
!      WRITE (*,106) ITREE
!106   FORMAT ('  TREE:',I5)


      CALL RESTARTMETF(ISTART,MSTART,MFLAG)
      
! Sort trees.
       CALL SORTTREES( &
       NOALLTREES,NOTREES,ITREE, &
       DXT1,DYT1,DZT1,RXTABLE1,RYTABLE1,RZTABLE1, &
       ZBCTABLE1,FOLTABLE1,DIAMTABLE1, &
       DXT,DYT,DZT,RXTABLE,RYTABLE,RZTABLE, &
       FOLTABLE,ZBCTABLE,DIAMTABLE, &
       ISPECIES,ISPECIEST)
       
! Assign arrays.
       ISPEC = ISPECIES(ITREE)

       JLEAF = JLEAFSPEC(ISPEC)
       BPT(1:8,1:MAXC) = BPTSPEC(1:8,1:MAXC,ISPEC)
       RANDOM = RANDOMSPEC(ISPEC)
       NOAGEC = NOAGECSPEC(ISPEC)
       JSHAPE = JSHAPESPEC(ISPEC)
       SHAPE = SHAPESPEC(ISPEC)
       EXTWIND = EXTWINDSPEC(ISPEC)
       NALPHA = NALPHASPEC(ISPEC)
       ALPHA(1:MAXANG) = ALPHASPEC(1:MAXANG,ISPEC)
       FALPHA(1:MAXANG) = FALPHASPEC(1:MAXANG,ISPEC)
       COEFFT = COEFFTSPEC(ISPEC)
       EXPONT = EXPONTSPEC(ISPEC)
       WINTERC = WINTERCSPEC(ISPEC)
       BCOEFFT = BCOEFFTSPEC(ISPEC)
       BEXPONT = BEXPONTSPEC(ISPEC)
       BINTERC = BINTERCSPEC(ISPEC)
       RCOEFFT = RCOEFFTSPEC(ISPEC)
       REXPONT = REXPONTSPEC(ISPEC)
       RINTERC = RINTERCSPEC(ISPEC)
       FRFRAC = FRFRACSPEC(ISPEC)
       
       NOAGEP      =  NOAGEPSPEC(ISPEC)       
       PROPC(1:MAXC) =  PROPCSPEC(1:MAXC,ISPEC)
       PROPP(1:MAXC) =  PROPPSPEC(1:MAXC,ISPEC)    
       ABSRP(1:MAXLAY,1:3) =  ABSRPSPEC(1:MAXLAY,1:3,ISPEC)  
       ARHO(1:MAXLAY,1:3) =  ARHOSPEC(1:MAXLAY,1:3,ISPEC)      
       ATAU(1:MAXLAY,1:3) =  ATAUSPEC(1:MAXLAY,1:3,ISPEC)       
       RHOSOL(1:3) =  RHOSOLSPEC(1:3,ISPEC)    
       JMAXTABLE(1:MAXDATE,1:MAXLAY,1:MAXC) = &
            JMAXTABLESPEC(1:MAXDATE,1:MAXLAY,1:MAXC,ISPEC) 
       DATESJ(1:MAXDATE) =  DATESJSPEC(1:MAXDATE,ISPEC)       
       NOJDATES    =  NOJDATESSPEC(ISPEC)     
       IECO        =  IECOSPEC(ISPEC)         
       EAVJ        =  EAVJSPEC(ISPEC)         
       EDVJ        =  EDVJSPEC(ISPEC)         
       DELSJ       =  DELSJSPEC(ISPEC)        
       THETA       =  THETASPEC(ISPEC)        
       VCMAXTABLE(1:MAXDATE,1:MAXLAY,1:MAXC) = &
            VCMAXTABLESPEC(1:MAXDATE,1:MAXLAY,1:MAXC,ISPEC)   
       DATESV(1:MAXDATE) =  DATESVSPEC(1:MAXDATE,ISPEC)         
       NOVDATES    =  NOVDATESSPEC(ISPEC)     
       EAVC        =  EAVCSPEC(ISPEC)         
       EDVC        =  EDVCSPEC(ISPEC)         
       DELSC       =  DELSCSPEC(ISPEC)        
       TVJUP       =  TVJUPSPEC(ISPEC)        
       TVJDN       =  TVJDNSPEC(ISPEC)        
       SLATABLE(1:MAXDATE,1:MAXLAY,1:MAXC) =  &
            SLATABLESPEC(1:MAXDATE,1:MAXLAY,1:MAXC,ISPEC)
       DATESSLA(1:MAXDATE) =  DATESSLASPEC(1:MAXDATE,ISPEC)       
       NOSLADATES  =  NOSLADATESSPEC (ISPEC)  
       NOADATES    =  NOADATESSPEC(ISPEC)   
       DATESA(1:MAXDATE) =  DATESASPEC(1:MAXDATE,ISPEC)         
       AJQTABLE(1:MAXDATE,1:MAXLAY,1:MAXC) =  &
            AJQTABLESPEC(1:MAXDATE,1:MAXLAY,1:MAXC,ISPEC)     
       RDTABLE(1:MAXDATE,1:MAXLAY,1:MAXC) =  &
           RDTABLESPEC(1:MAXDATE,1:MAXLAY,1:MAXC,ISPEC)      
       DATESRD(1:MAXDATE) =  DATESRDSPEC(1:MAXDATE,ISPEC)        
       NORDATES    =  NORDATESSPEC(ISPEC)     
       RTEMP       =  RTEMPSPEC(ISPEC)        
       DAYRESP     =  DAYRESPSPEC(ISPEC)      
       TBELOW      =  TBELOWSPEC(ISPEC)       
       EFFYRW      =  EFFYRWSPEC(ISPEC)       
       RMW         =  RMWSPEC(ISPEC)          
       RTEMPW      =  RTEMPWSPEC(ISPEC)       
       COLLA       =  COLLASPEC(ISPEC)        
       COLLK       =  COLLKSPEC(ISPEC)        
       STEMSDW     =  STEMSDWSPEC(ISPEC)      
       RMWAREA     =  RMWAREASPEC(ISPEC)      
       STEMFORM    =  STEMFORMSPEC(ISPEC)     
       NOFQDATES   =  NOFQDATESSPEC(ISPEC)    
       DATESFQ(1:MAXDATE) =  DATESFQSPEC(1:MAXDATE,ISPEC)        
       Q10FTABLE(1:MAXDATE) =  Q10FTABLESPEC(1:MAXDATE,ISPEC)    
       NOWQDATES   =  NOWQDATESSPEC(ISPEC)    
       DATESWQ     =  DATESWQSPEC(1:MAXDATE,ISPEC)      
       Q10WTABLE(1:MAXDATE) =  Q10WTABLESPEC(1:MAXDATE,ISPEC)    
       RMFR        =  RMFRSPEC(ISPEC)         
       RMCR        =  RMCRSPEC(ISPEC)         
       Q10R        =  Q10RSPEC(ISPEC)         
       RTEMPR      =  RTEMPRSPEC(ISPEC)       
       EFFYRF      =  EFFYRFSPEC(ISPEC)       
       RMB         =  RMBSPEC(ISPEC)          
       Q10B        =  Q10BSPEC(ISPEC)         
       RTEMPB      =  RTEMPBSPEC(ISPEC)      
       GSREF       =  GSREFSPEC(ISPEC)        
       GSMIN       =  GSMINSPEC(ISPEC)        
       PAR0        =  PAR0SPEC(ISPEC)         
       D0          =  D0SPEC(ISPEC)           
       VK1         =  VK1SPEC(ISPEC)         
       VK2         =  VK2SPEC(ISPEC)          
       VPD1        =  VPD1SPEC(ISPEC)         
       VPD2        =  VPD2SPEC(ISPEC)         
       VMFD0       =  VMFD0SPEC(ISPEC)        
       GSJA        =  GSJASPEC(ISPEC)         
       GSJB        =  GSJBSPEC(ISPEC)         
       T0          =  T0SPEC(ISPEC)           
       TREF        =  TREFSPEC(ISPEC)        
       TMAX        =  TMAXSPEC(ISPEC)         
       SMD1        =  SMD1SPEC(ISPEC)         
       SMD2        =  SMD2SPEC(ISPEC)        
       WC1         =  WC1SPEC(ISPEC)          
       WC2         =  WC2SPEC(ISPEC)          
       SWPEXP      =  SWPEXPSPEC(ISPEC)       
       G0          =  G0SPEC(ISPEC)           
       D0L         =  D0LSPEC(ISPEC)          
       GAMMA       =  GAMMASPEC(ISPEC)        
       G1          =  G1SPEC(ISPEC)     
       GK          =  GKSPEC(ISPEC)      
       WLEAF       =  WLEAFSPEC(ISPEC)        
       NSIDES      =  NSIDESSPEC(ISPEC)


! Assign sorted structure parameters. 
! RAD March 2009.
       DO I = 1,NOTREES
        JSHAPET(I) = JSHAPESPEC(ISPECIEST(I))
        SHAPET(I) = SHAPESPEC(ISPECIEST(I))
        DEXTT(I,1:MAXANG) = DEXTSPEC(ISPECIEST(I),1:MAXANG)
        JLEAFT(I) = JLEAFSPEC(ISPECIEST(I))
        NOAGECT(I) = NOAGECSPEC(ISPECIEST(I))
        BPTT(1:8,1:MAXC,I) = BPTSPEC(1:8,1:MAXC,ISPECIEST(I))
        PROPPT(1:MAXC,I) = PROPPSPEC(1:MAXC,ISPECIEST(I))
        PROPCT(1:MAXC,I) = PROPCSPEC(1:MAXC,ISPECIEST(I))
       ENDDO

! Empty PAR histogram.
      CALL ZEROSTART(HISTO,CANOPYDIMS)

!**********************************************************************
! Begin daily loop
      IDAY = 0
10    CONTINUE

! commented out by mgdk, 22 june, 2011
!      WRITE (*,105) IDAY
!105   FORMAT ('  DAY:',I5)

! Calculate zenith angle of sun
      CALL SUN(IDAY+ISTART,ALAT,TTIMD,DEC,EQNTIM,DAYL,SUNSET)
      CALL ZENAZ(ALAT,TTIMD,BEAR,DEC,EQNTIM,ZEN,AZ)

! Get meteorological data
      CALL GETMET(IDAY+ISTART,MFLAG,ZEN,METCOLS,NOMETCOLS, &
       CAK,PRESSK,SWMIN,SWMAX,DELTAT,ALAT,DEC,DAYL, &
       windah,tsoil,tair,radabv,fbeam,RH,VPD,VMFD,CA,PRESS, &
       PPT,SOILMOIST,SOILDATA)

      IF (ICC.EQ.0) CALL ALTERMETCC(CA,TAIR,TSOIL,RH,VPD,VMFD,PRESS, &
       CO2INC,TINC)
      IF (IOTC.EQ.0) CALL ALTERMETOTC(TOTC,WINDOTC,PAROTC,FBEAMOTC, &
       TAIR,TSOIL,WINDAH,RADABV,FBEAM,RH,VPD,VMFD,PRESS)

! Understorey diffuse radiation:
      IF(ISIMUS .EQ. 1 .AND. ITAR .EQ. 1)THEN
        IF((MOD(IDAY,IOTUTD).EQ.0).OR.IDAY.EQ.0)THEN

! Sort trees to middle of understorey points.
        AX = AVERAGEVAL(XLU,NOUSPOINTS)
        AY = AVERAGEVAL(YLU,NOUSPOINTS)

! Use *all trees* as target trees for the understorey!
        NOTREESUS = NOALLTREES 

!! Sort overstorey dimensions, save in separate arrays.
!! Can move this out of loop, only needs to be done once.
        CALL SORTTREESP( &
         AX,AY,NOALLTREES,NOTREES, &  ! NOTREES no longer used....
         DXT1,DYT1,DZT1,RXTABLE1,RYTABLE1,RZTABLE1, &
         ZBCTABLE1,FOLTABLE1,DIAMTABLE1, &
         DXTUS,DYTUS,DZTUS,RXTABLEUS,RYTABLEUS,RZTABLEUS, &
         FOLTABLEUS,ZBCTABLEUS,DIAMTABLEUS,ISPECIES,ISPECIESTUS)
    
! Interpolate overstorey dimensions for use in understorey calcs.
        CALL INTERPOLATET(IDAY,ISTART, &
         NOXDATES,DATESX,RXTABLEUS,NOYDATES,DATESY,RYTABLEUS, &
         NOZDATES,DATESZ,RZTABLEUS,NOTDATES,DATEST,ZBCTABLEUS, &
         NODDATES,DATESD,DIAMTABLEUS, &
         NOLADATES,DATESLA,FOLTABLEUS,TOTLAITABLE,NOTREESUS, &
         RXUS,RYUS,RZUS,ZBCUS,FOLTUS,TOTLAI,DIAM,STOCKING, &
         IFLUSH,DT1,DT2,DT3,DT4,EXPTIME,APP,EXPAN, &
         NEWCANOPY,CANOPYDIMS)
     
! Interpolate understorey dimensions
        CALL INTERPUS(IDAY,ISTART, &
         NOUSPOINTS,UNMIN,EXTKUS,GRDAREAI, &
         DATESFU,NOFUDATES,USLAITAB,USLAI, &
         DATESHU,NOHUDATES,HTUS,ZLU, &
         DATESNU,NONUDATES,FOLNUS,FN0US, &
         AREAUS)

! Make tree arrays of radiation-extinction related parameters,
! that may vary between species.
       DO I = 1,NOTREESUS
        JSHAPETUS(I) = JSHAPESPEC(ISPECIESTUS(I))
        SHAPETUS(I) = SHAPESPEC(ISPECIESTUS(I))
        DEXTTUS(I,1:MAXANG) = DEXTSPEC(ISPECIESTUS(I),1:MAXANG)
        JLEAFTUS(I) = JLEAFSPEC(ISPECIESTUS(I))
        NOAGECTUS(I) = NOAGECSPEC(ISPECIESTUS(I))
        BPTTUS(1:8,1:MAXC,I) = BPTSPEC(1:8,1:MAXC,ISPECIESTUS(I))
        PROPPTUS(1:MAXC,I) = PROPPSPEC(1:MAXC,ISPECIESTUS(I))
        PROPCTUS(1:MAXC,I) = PROPCSPEC(1:MAXC,ISPECIESTUS(I))
       ENDDO

! Diffuse transmission to the understorey points.
       CALL TRANSD(  &
       IDAY,IOTUTD,NEWCANOPY,IPROGUS,NOTREESUS,XSLOPE,YSLOPE, &
       NZEN,DIFZEN,NAZ,NOUSPOINTS,DEXTTUS,DIFSKY, &
       XLU,YLU,ZLU,RXUS,RYUS,RZUS,DXTUS,DYTUS,DZTUS, &
       XMAX,YMAX,SHADEHT, &
       FOLTUS,ZBCUS,JLEAFTUS,BPTTUS, &
       NOAGECTUS,PROPCTUS,JSHAPETUS,SHAPETUS, &
       NEWTUTD,TUUS,TDUS,RELDFP,DEXTP)          !!!! WHY DEXTP ????
    
       ENDIF
     ENDIF ! End understorey diffuse calculations


! Interpolate to get daily values of parameters
      CALL INTERPOLATEP(IDAY,ISTART,NOJDATES,DATESJ,JMAXTABLE, &
       NOVDATES,DATESV,VCMAXTABLE,NORDATES,DATESRD,RDTABLE, &
       NOSLADATES,DATESSLA,SLATABLE,NOADATES,DATESA,AJQTABLE, &
       NOFQDATES,DATESFQ,Q10FTABLE,NOWQDATES,DATESWQ,Q10WTABLE, &
       NOLAY,NOAGEP,JMAX25,VCMAX25,RD0,SLA,AJQ,Q10F,Q10W)
     
      CALL INTERPOLATET(IDAY,ISTART, &
       NOXDATES,DATESX,RXTABLE,NOYDATES,DATESY,RYTABLE, &
       NOZDATES,DATESZ,RZTABLE,NOTDATES,DATEST,ZBCTABLE, &
       NODDATES,DATESD,DIAMTABLE, &
       NOLADATES,DATESLA,FOLTABLE,TOTLAITABLE,NOTREES, &
       RX,RY,RZ,ZBC,FOLT,TOTLAI,DIAM,STOCKING, &
       IFLUSH,DT1,DT2,DT3,DT4,EXPTIME,APP,EXPAN, &
       NEWCANOPY,CANOPYDIMS)

! MAESHR
! Print initial output to ptflux.dat
!      WRITE (UPT,*) 'DETAILS OF TARGET TREE'
!      WRITE (UPT,510) 'X: ',DXT(1),' Y: ',DYT(1),
!     +  ' HEIGHT: ',RZ(1)+ZBC(1)
!      WRITE (UPT,510) ' DIAM: ',DIAM(1),' RADIUS: ',RX(1)
!      TREELAI = FOLT(1)/(RX(1)*RY(1)*PI)
!      WRITE (UPT,510) ' LEAF AREA: ',FOLT(1),' TREE LAI: ',TREELAI,
!     +  ' STAND LAI: ',TOTLAI
!510   FORMAT(3(A12,F8.3))


      IF (NEWCANOPY.EQ.1) THEN
!! If the canopy has changed (or on the first day) the grid points must be set up
!        CALL Points(
!     &    NUMPNT,JLEAF,JSHAPE,SHAPE,RX(1),RY(1),RZ(1),
!     &    ZBC(1),DXT(1),DYT(1),DZT(1),FOLT(1),
!     &    PROPC,PROPP,BPT,NOAGEC,NOAGEP,NOLAY,
!     &    XL,YL,ZL,VL,DLT,DLI,LGP,FOLLAY
!     &  )
        
       ! New version of POINTS subroutine, takes nr. of points per layer (PPLAY) as input.
       CALL POINTSNEW( &
       NOLAY,PPLAY,JLEAF,JSHAPE,SHAPE,RX(1),RY(1),RZ(1),  &
       ZBC(1),DXT(1),DYT(1),DZT(1),FOLT(1),PROPC,PROPP, &
       BPT,NOAGEC,NOAGEP, &
       XL,YL,ZL,VL,DLT,DLI,LGP,FOLLAY &
       )
       
     
      END IF

      ! Write XYZ coordinates of the current grid points to a file.
!      DO I = 1,PPLAY*NOLAY
!        WRITE(99, *)XL(I),YL(I),ZL(I)
!      ENDDO
      
      
      ! Do Maestest calculations (only once - when the loop is at the first tree (ITAR), and on the first day).
      IF(IPOINTS.EQ.1.AND.ITAR.EQ.1.AND.IDAY.EQ.0)THEN
   
! Sort trees to middle of test points (has no real effect at the moment; since all trees in the plot are used).
        AX = AVERAGEVAL(XLP,NUMTESTPNT)
        AY = AVERAGEVAL(YLP,NUMTESTPNT)

! Use *all trees* as target trees for the test points.
        IPROGCUR = ITEST
        NOTREESTEST = NOALLTREES

!! Sort overstorey dimensions, save in separate arrays.
!! Can move this out of loop, only needs to be done once.
        CALL SORTTREESP( &
         AX,AY,NOALLTREES,NOTREES, &  ! NOTREES no longer used in SORTTREESP
         DXT1,DYT1,DZT1,RXTABLE1,RYTABLE1,RZTABLE1, &
         ZBCTABLE1,FOLTABLE1,DIAMTABLE1, &
         DXTP,DYTP,DZTP,RXTABLEP,RYTABLEP,RZTABLEP, &
         FOLTABLEP,ZBCTABLEP,DIAMTABLEP,ISPECIES,ISPECIESTP)
    
! Interpolate overstorey dimensions for use in test point calcs.
        CALL INTERPOLATET(IDAY,ISTART, &
         NOXDATES,DATESX,RXTABLEP,NOYDATES,DATESY,RYTABLEP, &
         NOZDATES,DATESZ,RZTABLEP,NOTDATES,DATEST,ZBCTABLEP, &
         NODDATES,DATESD,DIAMTABLEP, &
         NOLADATES,DATESLA,FOLTABLEP,TOTLAITABLE,NOTREESTEST, &
         RXP,RYP,RZP,ZBCP,FOLTP,TOTLAI,DIAM,STOCKING, &
         IFLUSH,DT1,DT2,DT3,DT4,EXPTIME,APP,EXPAN, &
         NEWCANOPY,CANOPYDIMS)
     
! Make tree arrays of radiation-extinction related parameters,
! that may vary between species.
       DO I = 1,NOTREESTEST
        JSHAPETP(I) = JSHAPESPEC(ISPECIESTP(I))
        SHAPETP(I) = SHAPESPEC(ISPECIESTP(I))
        DEXTTP(I,1:MAXANG) = DEXTSPEC(ISPECIESTP(I),1:MAXANG)
        JLEAFTP(I) = JLEAFSPEC(ISPECIESTP(I))
        NOAGECTP(I) = NOAGECSPEC(ISPECIESTP(I))
        BPTTP(1:8,1:MAXC,I) = BPTSPEC(1:8,1:MAXC,ISPECIESTP(I))
        PROPPTP(1:MAXC,I) = PROPPSPEC(1:MAXC,ISPECIESTP(I))
        PROPCTP(1:MAXC,I) = PROPCSPEC(1:MAXC,ISPECIESTP(I))
       ENDDO

       CALL TRANSD( &
        IDAY,IOTUTD,NEWCANOPY,IPROGCUR,NOTREESTEST,XSLOPE,YSLOPE, &
        NZEN,DIFZEN,NAZ,NUMTESTPNT,DEXTTP,DIFSKY, &
        XLP,YLP,ZLP,RXP,RYP,RZP,DXTP,DYTP,DZTP, &
        XMAX,YMAX,SHADEHT, &
        FOLTP,ZBCP,JLEAFTP,BPTTP,NOAGECTP,PROPCTP,JSHAPETP,SHAPETP, &
        NEWTUTD,TUP,TDP,RELDFP,DEXTP)
      
       !DO I = 1,NUMTESTPNT
       !  WRITE(99, *)XLP(I),YLP(I),TUP(I),TDP(I),RELDFP(I)
       !ENDDO
     
! If the diffuse transmittances have changed, must set up the EHC
        CALL EHC(NUMTESTPNT,TUP,TDP, &
         TOTLAI,XSLOPE,YSLOPE,NAZ,NZEN,DIFZEN,DEXTP, &
         DLAIP,EXPDIFP,LAYERP,MLAYERP &
       )     
          
      ENDIF  ! MAESTEST (Diffuse calculations)

! Following functions need FOLLAY. 
      CALL GETWIND(FOLLAY,FOLT(1),TOTLAI,EXTWIND,WINDLAY)
! Calculate woody biomass and woody biomass increment
      CALL CALCWBIOM(IDAY,RZ(1)+ZBC(1),DIAM(1),COEFFT,EXPONT,WINTERC, &
       WBIOM,WBINC)
      CALL CALCWBIOM(IDAY,RZ(1)+ZBC(1),DIAM(1),BCOEFFT,BEXPONT,BINTERC, &
       BBIOM,BBINC)
      CALL CALCWBIOM(IDAY,RZ(1)+ZBC(1),DIAM(1),RCOEFFT,REXPONT,RINTERC, &
       RBIOM,RBINC)
! Calculate foliar biomass and increment
      CALL CALCFBIOM(IDAY,NOSLADATES,FOLLAY,SLA,PROPP,NOLAY,NOAGEP, &
       FBIOM,FBINC)
! Calculate stem respiration rate per unit biomass
    RMW = CALCRMW(MODELRW,COLLA,COLLK,STEMSDW, &
       DIAM(1),RZ(1)+ZBC(1),STEMFORM,RMWAREA,WBIOM,RMW)

! Output information to layer flux file if required
      IF (IOHRLY.GT.1) &
       CALL OUTPUTLAY(ULAY,FOLLAY,JMAX25,VCMAX25,NOLAY)

! Calculate diffuse transmittances
! Modified for multi-species option (RAD, March 2009).
! Note that DEXT is output (path-length weighted extinction 
! coefficient).
      CALL TRANSD( &
       IDAY,IOTUTD,NEWCANOPY,IPROG,NOTREES,XSLOPE,YSLOPE, &
       NZEN,DIFZEN,NAZ,NUMPNT,DEXTT,DIFSKY, &
       XL,YL,ZL,RX,RY,RZ,DXT,DYT,DZT, &
       XMAX,YMAX,SHADEHT, &
       FOLT,ZBC,JLEAFT,BPTT,NOAGECT,PROPCT,JSHAPET,SHAPET, &
       NEWTUTD,TU,TD,RELDF,DEXT &
       )

      IF (NEWTUTD.EQ.1) THEN
! If the diffuse transmittances have changed, must set up the EHC
        CALL EHC(NUMPNT,TU,TD, &
         TOTLAI,XSLOPE,YSLOPE,NAZ,NZEN,DIFZEN,DEXT, &
         DLAI,EXPDIF,LAYER,MLAYER &
       )
      END IF

! MAESHR
!      WRITE(UPT,*)
!      WRITE(UPT,*) 'MET DATA FOR HOUR NO ',IHRNO
!      WRITE(UPT,510) ' PAR: ',RADABV(IHRNO,1)*UMOLPERJ,
!     +  ' FBEAM: ',FBEAM(IHRNO,1)
!      WRITE(UPT,510) ' ZENITH: ',ZEN(IHRNO)/PID180,
!     +  ' AZIMUTH: ',AZ(IHRNO)/PID180
!      WRITE(UPT,510) ' TAIR: ',TAIR(IHRNO),' CA: ',CA(IHRNO),
!     +  'VPD: ',VPD(IHRNO)
!      WRITE(UPT,*)


! Zero daily fluxes
      CALL ZEROD(TDYAB,TOTCO2,TOTRESPF,TOTRESPWM, &
       TOTRESPB,TOTRESPCR,TOTRESPFR,TOTH2O,TOTHFX,TOTH2OCAN)
! Zero hourly fluxes
      CALL ZEROHR(THRAB,FCO2,FRESPF,FRESPW,FRESPB,FRESPFR,FRESPCR, &
       FH2O,GSCAN,FHEAT,PPAR,PPS,PTRANSP,TCAN,DECOUPL,FH2OCAN)

!**********************************************************************
! Begin hourly loop
      DO 100 IHOUR = 1,KHRS

! MAESHR
      !DO 100 IHOUR = IHRNO,IHRNO

! Test to see if daylight hours or if any foliage
        IF ((ABS(ZEN(IHOUR)).LE. PI/2.0).AND. &
         (RADABV(IHOUR,1).GT.1.0).AND. &
         (FOLT(1).GT.0.0)) THEN

! Comments for this hour
        PAR = RADABV(IHOUR,1)*UMOLPERJ
!        WRITE(UPOINTSO,980) IHOUR,PAR,ZEN(IHOUR)/PID180,AZ(IHOUR)/PID180
!980     FORMAT ('HOUR: ',I2,'  INCIDENT PAR: ',3(F8.2,1X))

! Get slope correction factor
          CALL SLOPES(IHOUR,TTIMD,EQNTIM,ALAT,DEC, &
           XSLOPE,YSLOPE,BEAR,ZEN(IHOUR), &
           BMULT,DMULT2,SOMULT)

! Get extinction coefficient for beam radiation
! Modified for multi-species option (RAD, March 2009).
        DO I=1,NSPECIES
          CALL EXBEAM(NALPHASPEC(I),ALPHASPEC(1:MAXANG,I), &
           FALPHASPEC(1:MAXANG,I),RANDOMSPEC(I),ZEN(IHOUR), &
           BEXTSPEC(I),BEXTANGSPEC(I,1:MAXANG))
       ENDDO

! Assign sorted arrays (extinction coefficients for direct radiation).
       DO I=1,NOTREES
            BEXTT(I) = BEXTSPEC(ISPECIEST(I))
            BEXTANGT(I,1:MAXANG) = BEXTANGSPEC(ISPECIEST(I),1:MAXANG)
       ENDDO
       
! Understorey calculations.
          IF(ISIMUS.EQ.1 .AND. ITAR.EQ.1)THEN

! Find extinction coefficients for beam component,
! sorted to understorey midpoint (ISPECIESTUS).
          DO I=1,NOTREESUS
            BEXTTUS(I) = BEXTSPEC(ISPECIESTUS(I))
            BEXTANGTUS(I,1:MAXANG) = BEXTANGSPEC(ISPECIESTUS(I),1:MAXANG)
          ENDDO

           DO IPTUS = 1,NOUSPOINTS

! Beam radiation on the understorey points.
            CALL TRANSB(IHOUR,IPROGUS, &
             ZEN(IHOUR),AZ(IHOUR),XSLOPE,YSLOPE,FBEAM,BEXTTUS, &
             XLU(IPTUS),YLU(IPTUS),ZLU(IPTUS), &
             RXUS,RYUS,RZUS,DXTUS,DYTUS,DZTUS, &
             XMAX,YMAX,SHADEHT,FOLTUS,ZBCUS,JLEAFTUS, &
             BPTTUS,NOAGECTUS,PROPCTUS,JSHAPETUS,SHAPETUS, &
             NOTREESUS,SUNLA,BEXTUS)  ! BEXTUS is not used...
            
! Output transmittances (Note IWAVE=1 only).
            PAR = RADABV(IHOUR,1)
            TDIFF = (1-FBEAM(IHOUR,1))*PAR*TDUS(IPTUS)
            TSCAT = 0 !DIFDN(IPTUS,1)*UMOLPERJ
            
! PAR at all understorey points, diffuse, direct, and total.
            UIBEAM(IHOUR,IPTUS) = FBEAM(IHOUR,1)*PAR*SUNLA
            UIDIFF(IHOUR,IPTUS) = TDIFF + TSCAT
            PARUS(IHOUR,IPTUS) = UIDIFF(IHOUR,IPTUS) + UIBEAM(IHOUR,IPTUS)
          
! Get (temperature dependent) parameters of BEWDY model
          CALL BEWDYPARMS(IHOUR,TAIR(IHOUR),RH(IHOUR),CA(IHOUR), &
           JMAXN25,IECOU,EAVJU,EDVJU,DELSJU,TVJUPU,TVJDNU, &
           VCMAXN25,EAVCU,EDVCU,DELSCU,AJQU,GSBG0U,GSBG1U, &
           CICARAT,BALPHA,BLAMBDA)
          
! Moss photosynthesis.
          IF (MOSS.EQ.1) THEN

            CALL PSMOSS(UMOLPERJ*PARUS(IHOUR,IPTUS),TAIR(IHOUR),RH(IHOUR), &
               CA(IHOUR),JMAX25M,IECOU,EAVJU,EDVJU,DELSJU,TVJUPU,TVJDNU, &
               VCMAX25M,EAVCU,EDVCU,DELSCU,AJQU,THETAM,PSUS(IHOUR,IPTUS))
            
            ! Gs and E not calculated for moss (for some reason).
            GSIPT = 0.0
            ETUS = 0.0

          ELSE
          
! Otherwise call BEWDY model to calculate understorey photosynthesis       
            IF(SUNLA.GT.0.0) THEN
                BEAMP = UMOLPERJ*UIBEAM(IHOUR,IPTUS)/SUNLA
            ELSE
                BEAMP = 0.0
            ENDIF
            
            CALL BEWDY(IHOUR,BEAMP,UMOLPERJ*UIDIFF(IHOUR,IPTUS), &
             SUNLA,BALPHA,BLAMBDA,FN0US(IPTUS), &
             UNMIN,EXTKUS,ABSRPU,USLAI(IPTUS), &
             APARUS(IHOUR,IPTUS),PSUS(IHOUR,IPTUS),PARUNDER(IHOUR,IPTUS))

            ! Bewdy outputs in mu mol, convert to W m-2 (to match UIBEAM and others for output).
            APARUS(IHOUR,IPTUS) = APARUS(IHOUR,IPTUS) / UMOLPERJ
            PARUNDER(IHOUR,IPTUS) = PARUNDER(IHOUR,IPTUS) / UMOLPERJ

            ! Stomatal conductance and transpiration (Ball-Berry model....)
            GSIPT = GSBG0U + GSBG1U*PSUS(IHOUR,IPTUS) * RH(IHOUR)/CA(IHOUR)    ! mol CO2 m-2 s-1
            ETUS(IHOUR,IPTUS) = GSIPT*1.6*VPD(IHOUR)/PRESS(IHOUR)*1E3        ! mmol H2O m-2 s-1
            
            END IF

          ENDDO ! Loop over understorey points.
          
          ! Sum understorey arrays over all points:
          CALL SUMHRUS(IHOUR,NOUSPOINTS,GRDAREAI,AREAUS,PARUS, &
               PARUSMEAN,PARUSSD,APARUS,PSUS,ETUS,THRABUS, &
               FCO2US,FH2OUS)
          
          ENDIF ! Understorey calculations
          

!!!!! MAESTEST: get radiation at pre-defined points.    
      IF(IPOINTS.EQ.1)THEN      
      DO IPTEST = 1,NUMTESTPNT
          
      IPROGCUR = ITEST

      DO I=1,NOTREESTEST
            BEXTTP(I) = BEXTSPEC(ISPECIESTP(I))
            BEXTANGTP(I,1:MAXANG) = BEXTANGSPEC(ISPECIESTP(I),1:MAXANG)
      ENDDO

      CALL TRANSB(IHOUR,IPROGCUR, &
             ZEN(IHOUR),AZ(IHOUR),XSLOPE,YSLOPE,FBEAM,BEXTTP, &
             XLP(IPTEST),YLP(IPTEST),ZLP(IPTEST),RXP,RYP,RZP,DXTP,DYTP,DZTP, &
             XMAX,YMAX,SHADEHT, &
             FOLTP,ZBCP,JLEAFTP,BPTTP,NOAGECTP,PROPCTP,JSHAPETP,SHAPETP, &
             NOTREESTEST,SUNLAP,BEXTP)

      IWAVE = 1 !(As in original MAESTEST, use only PAR.
      CALL SCATTER(IPTEST,IWAVE, &
               MLAYERP(IPTEST),LAYERP(IPTEST),DLAIP,EXPDIFP, &
               ZEN(IHOUR),BEXTP, &
               DMULT2,SOMULT,BMULT, &
               RADABV(IHOUR,IWAVE),FBEAM(IHOUR,IWAVE), &
               TAIR(IHOUR),TSOIL(IHOUR), &
               ARHO(1,IWAVE),ATAU(1,IWAVE), &    ! Note 1 here instead of LGP().
               RHOSOL(IWAVE), &
               DIFUP,DIFDN,SCLOST)
!
!      CALL ABSRAD(IPTEST,IWAVE, &
!               NZEN,DEXT,BEXT,BMULT,RELDFP(IPTEST), &
!               RADABV(IHOUR,IWAVE),FBEAM(IHOUR,IWAVE),ZEN(IHOUR), &
!               ABSRP(1,IWAVE),DIFDN(IPTEST,IWAVE), &
!               DIFUP(IPTEST,IWAVE), &
!               DFLUX,BFLUX,SCATFX)

! Output transmittances
      PAR = RADABV(IHOUR,1)*UMOLPERJ
      TBEAM = FBEAM(IHOUR,IWAVE)*PAR*SUNLAP
      TDIFF = (1-FBEAM(IHOUR,IWAVE))*PAR*TDP(IPTEST)
      TSCAT = DIFDN(IPTEST,IWAVE)
      TTOT = TBEAM + TDIFF + TSCAT
!
!      ! Photosynthesis, stomatal conductance, etc.
!      DO ISUNLIT = 1,2 ! Loop over sunlit & shaded leaves
!
!              IF (ISUNLIT.EQ.1) THEN
!                APAR = (BFLUX(IPTEST,1)*BEXT + DFLUX(IPTEST,1))*UMOLPERJ
!                ANIR = BFLUX(IPTEST,2)*BEXT + DFLUX(IPTEST,2)
!              ELSE
!                APAR = DFLUX(IPTEST,1)*UMOLPERJ
!                ANIR = DFLUX(IPTEST,2)
!              END IF
!
!              ATHR = DFLUX(IPTEST,3)
!              RNET = APAR/UMOLPERJ + ANIR + ATHR
!
!! Call physiology routine (MAESTEST).
!!!! MULTIPLE AGE CLASSES ARE IGNORED!!!
!                CALL PSTRANSP(RELDFP(IPTEST),TU(IPTEST),TD(IPTEST),RNET, &
!       WINDAH(IHOUR)*WINDLAY(LGP(IPTEST)),APAR,TAIR(IHOUR),CA(IHOUR), &
!       RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR), &
!       JMAX25(LGP(IPTEST),1),IECO,EAVJ,EDVJ,DELSJ, &
!       VCMAX25(LGP(IPTEST),1),EAVC,EDVC,DELSC,TVJUP,TVJDN, &
!       THETA,AJQ(LGP(IPTEST), 1),RD0(LGP(IPTEST),1), &
!       Q10F,RTEMP,DAYRESP,TBELOW, &
!       MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0, &
!       GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP, &
!       G0,D0L,GAMMA,G1,GK,WLEAF,NSIDES,ITERMAX, &
!       GSCTEST(IPTEST,ISUNLIT),ALEAFTEST(IPTEST,ISUNLIT), &
!       RDTEST(IPTEST,ISUNLIT),ETTEST(IPTEST,ISUNLIT), &
!       HFX,TLEAF,GBH,DECOUP)
!      
!      ENDDO      

!      ! WRITE OUTPUT TO TESTFLX.DAT      
!      WRITE (UPOINTSO,501) IDAY,IHOUR,IPTEST,PAR,FBEAM(IHOUR,1),SUNLAP, &
!         TDP(IPTEST),TSCAT,TTOT,GSCTEST(IPTEST,1),GSCTEST(IPTEST,2), &
!         ALEAFTEST(IPTEST,1),ALEAFTEST(IPTEST,2),RDTEST(IPTEST,1), &
!         ETTEST(IPTEST,1)/1000,ETTEST(IPTEST,2)/1000
!501   FORMAT(3(I3,1X),14(F12.5,1X))

      WRITE (UPOINTSO,501) IDAY,IHOUR,IPTEST,XLP(IPTEST),YLP(IPTEST),ZLP(IPTEST), &
         PAR,FBEAM(IHOUR,1),SUNLAP,TDP(IPTEST),TSCAT,TTOT
501   FORMAT(3(I5,1X),9(F12.5,1X))


           
      ENDDO  
      ENDIF  !MAESTEST          
   
   
! Loop over grid points
          DO 80 IPT = 1,NUMPNT

! Calculate the weighted pathlengths for beam radiation.
! Modified for multi-species option (RAD, March 2009).
! Note that BEXT is output (path-length weighted extinction 
! coefficient - corrected for the possibility that the beam passes through 
! crowns with different leaf angle distributions).
            !!!!! Code change. Sunla is now calculated regardless of whether FBEAM > 0 or not.
            ! It is then output (SUNLAPOT), and can be interpreted as the 'potential sunlit area'.
            CALL TRANSB(IHOUR,IPROG, &
             ZEN(IHOUR),AZ(IHOUR),XSLOPE,YSLOPE,FBEAM,BEXTT, &
             XL(IPT),YL(IPT),ZL(IPT),RX,RY,RZ,DXT,DYT,DZT, &
             XMAX,YMAX,SHADEHT, &
             FOLT,ZBC,JLEAFT,BPTT,NOAGECT,PROPCT,JSHAPET,SHAPET, &
             NOTREES,SUNLAPOT,BEXT)
         
         IF(FBEAM(IHOUR,1).EQ.0.0.AND.FBEAM(IHOUR,2).EQ.0.0)THEN
                SUNLA = 0.0
         ELSE
                SUNLA = SUNLAPOT
         ENDIF
         
         ! Write sunlit leaf area to file.
         IF(ISUNLA.EQ.1)THEN
             AREA = DLI(1,IPT) * VL(IPT)  ! LEAF AREA FOR THIS GRIDPOINT
             WRITE(USUNLA, 112)IDAY, IHOUR, ITREE, IPT, SUNLAPOT, SUNLA, &
                  AREA, BEXT, &
                  FBEAM(IHOUR,1), XL(IPT),YL(IPT),ZL(IPT)
112      FORMAT(4(1X,I4), 8(1X,F12.3))
         ENDIF
         
         
! Loop over the 3 wavelengths
            DO 90 IWAVE = 1,3

! Calculate the scattered radiation
              CALL SCATTER(IPT,IWAVE, &
               MLAYER(IPT),LAYER(IPT),DLAI,EXPDIF, &
               ZEN(IHOUR),BEXT, &
               DMULT2,SOMULT,BMULT, &
               RADABV(IHOUR,IWAVE),FBEAM(IHOUR,IWAVE), &
               TAIR(IHOUR),TSOIL(IHOUR), &
               ARHO(LGP(IPT),IWAVE),ATAU(LGP(IPT),IWAVE),RHOSOL(IWAVE), &
               DIFUP,DIFDN,SCLOST)

! Calculate absorbed radiation
              CALL ABSRAD(IPT,IWAVE, &
               NZEN,DEXT,BEXT,BMULT,RELDF(IPT), &
               RADABV(IHOUR,IWAVE),FBEAM(IHOUR,IWAVE),ZEN(IHOUR), &
               ABSRP(LGP(IPT),IWAVE),DIFDN(IPT,IWAVE),DIFUP(IPT,IWAVE), &
               DFLUX,BFLUX,SCATFX)

90          CONTINUE ! End loop over wavelengths


! Calculation of photosynthesis may be done for sunlit & shaded leaves
! separately, or by averaging PAR over the total leaf area

            IF ((MODELSS.EQ.0).AND.(FBEAM(IHOUR,1).NE.0.0)) THEN 
! Do calculations separately for sunlit & shaded leaves

            DO 95 ISUNLIT = 1,2 ! Loop over sunlit & shaded leaves

              IF (ISUNLIT.EQ.1) THEN
                APAR = (BFLUX(IPT,1)*BEXT + DFLUX(IPT,1))*UMOLPERJ
                ANIR = BFLUX(IPT,2)*BEXT + DFLUX(IPT,2)
                FAREA = SUNLA

              ELSE
                APAR = DFLUX(IPT,1)*UMOLPERJ
                ANIR = DFLUX(IPT,2)
                FAREA = 1.0 - SUNLA
              END IF

              ATHR = DFLUX(IPT,3)
              RNET = APAR/UMOLPERJ + ANIR + ATHR

              DO 95 IAGE = 1,NOAGEP ! Loop over age classes
                AREA = FAREA * DLI(IAGE,IPT) * VL(IPT) ! m2
                IF (IOHIST.EQ.1) CALL CATEGO(AREA,APAR,HISTO,BINSIZE)

! Call physiology routine
                CALL PSTRANSP(RELDF(IPT),TU(IPT),TD(IPT),RNET, &
       WINDAH(IHOUR)*WINDLAY(LGP(IPT)),APAR,TAIR(IHOUR),CA(IHOUR), &
       RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR), &
       JMAX25(LGP(IPT),IAGE),IECO,EAVJ,EDVJ,DELSJ, &
       VCMAX25(LGP(IPT),IAGE),EAVC,EDVC,DELSC,TVJUP,TVJDN, &
       THETA,AJQ(LGP(IPT),IAGE),RD0(LGP(IPT),IAGE), &
       Q10F,RTEMP,DAYRESP,TBELOW, &
       MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0, &
       GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP, &
       G0,D0L,GAMMA,G1,GK,WLEAF,NSIDES,ITERMAX, &
        GSC,ALEAF,RD,ET,HFX,TLEAF,GBH,DECOUP)

!! MAESHR
!                CALL PSTRANSP(RELDF(IPT),TU(IPT),TD(IPT),RNET,
!     +  WINDAH(IHOUR)*WINDLAY(LGP(IPT)),APAR,TAIR(IHOUR),CA(IHOUR),
!     +  RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR),
!     +  JMAX25(LGP(IPT),IAGE),IECO,EAVJ,EDVJ,DELSJ,
!     +  VCMAX25(LGP(IPT),IAGE),EAVC,EDVC,DELSC,TVJUP,TVJDN,
!     +  THETA,AJQ(LGP(IPT),IAGE),RD0(LGP(IPT),IAGE),
!     &  Q10F,RTEMP,DAYRESP,TBELOW,
!     +  MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0,
!     &  GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP,
!     +  G0,D0L,GAMMA,G1,WLEAF,NSIDES,ITERMAX,
!     +  GSCHR(IPT,ISUNLIT),ALEAFHR(IPT,ISUNLIT),RDHR(IPT,ISUNLIT),
!     +  ETHR(IPT,ISUNLIT),HFXHR(IPT,ISUNLIT),
!     +  TLEAFHR(IPT,ISUNLIT),GBHHR(IPT,ISUNLIT),DECOUP)

! Sum outputs for the hour
              CALL SUMHR(APAR/UMOLPERJ,ANIR,ATHR, &
       ALEAF,RD,GSC,ET,HFX,TLEAF, &
       AREA,IHOUR,LGP(IPT), &
       PPAR,PPS,PTRANSP, &
       THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN, &
       DECOUP,DECOUPL)

!! MAESHR Sum outputs for the hour
!              CALL SUMHR(APAR/UMOLPERJ,ANIR,ATHR,
!     +  ALEAFHR(IPT,ISUNLIT),RDHR(IPT,ISUNLIT),
!     +  GSCHR(IPT,ISUNLIT),ETHR(IPT,ISUNLIT),
!     &  HFXHR(IPT,ISUNLIT),TLEAFHR(IPT,ISUNLIT),
!     +  AREA,IHOUR,LGP(IPT),
!     +  PPAR,PPS,PTRANSP,
!     +  THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN,
!     +  DECOUP,DECOUPL)

!    write(*,*) ihour,ipt,apar/umolperj,area,thrab(ihour,1)*umolperj

95          CONTINUE ! End loop over sunlit / shaded leaves

            ELSE IF ((MODELSS.EQ.1).OR.(FBEAM(IHOUR,1).EQ.0.0)) THEN 
! Do calculations for PAR averaged over all leaf area

              APAR = (BFLUX(IPT,1)*BEXT*SUNLA + DFLUX(IPT,1))*UMOLPERJ
              ANIR = BFLUX(IPT,2)*BEXT*SUNLA + DFLUX(IPT,2)
              ATHR = DFLUX(IPT,3)
              RNET = APAR/UMOLPERJ + ANIR + ATHR

              DO 125 IAGE = 1,NOAGEP ! Loop over age classes
                AREA = DLI(IAGE,IPT) * VL(IPT)
                IF (IOHIST.EQ.1) CALL CATEGO(AREA,APAR,HISTO,BINSIZE)

! Call physiology routine
                CALL PSTRANSP(RELDF(IPT),TU(IPT),TD(IPT),RNET, &
       WINDAH(IHOUR)*WINDLAY(LGP(IPT)),APAR,TAIR(IHOUR),CA(IHOUR), &
       RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR), &
       JMAX25(LGP(IPT),IAGE),IECO,EAVJ,EDVJ,DELSJ, &
       VCMAX25(LGP(IPT),IAGE),EAVC,EDVC,DELSC,TVJUP,TVJDN, &
       THETA,AJQ(LGP(IPT),IAGE),RD0(LGP(IPT),IAGE), &
       Q10F,RTEMP,DAYRESP,TBELOW, &
       MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0, &
       GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP, &
       G0,D0L,GAMMA,G1,GK,WLEAF,NSIDES,ITERMAX, &
       GSC,ALEAF,RD,ET,HFX,TLEAF,GBH,DECOUP)

      
      !write(uwattest,*)gamma

!! MAESHR
!        CALL PSTRANSP(RELDF(IPT),TU(IPT),TD(IPT),RNET,
!     +  WINDAH(IHOUR)*WINDLAY(LGP(IPT)),APAR,TAIR(IHOUR),CA(IHOUR),
!     +  RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR),
!     +  JMAX25(LGP(IPT),IAGE),IECO,EAVJ,EDVJ,DELSJ,
!     +  VCMAX25(LGP(IPT),IAGE),EAVC,EDVC,DELSC,TVJUP,TVJDN,
!     +  THETA,AJQ(LGP(IPT),IAGE),RD0(LGP(IPT),IAGE),
!     &  Q10F,RTEMP,DAYRESP,TBELOW,
!     +  MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0,
!     &  GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP,
!     +  G0,D0L,GAMMA,G1,WLEAF,NSIDES,ITERMAX,
!     +  GSCHR(IPT,ISUNLIT),ALEAFHR(IPT,ISUNLIT),RDHR(IPT,ISUNLIT),
!     +  ETHR(IPT,ISUNLIT),HFXHR(IPT,ISUNLIT),
!     +  TLEAFHR(IPT,ISUNLIT),GBHHR(IPT,ISUNLIT),DECOUP)
     
! Sum outputs for the hour
              CALL SUMHR(APAR/UMOLPERJ,ANIR,ATHR, &
       ALEAF,RD,GSC,ET,HFX,TLEAF, &
       AREA,IHOUR,LGP(IPT), &
       PPAR,PPS,PTRANSP, &
       THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN, &
       DECOUP,DECOUPL)

!! MAESHR
!              CALL SUMHR(APAR/UMOLPERJ,ANIR,ATHR,
!     +  ALEAFHR(IPT,1),RDHR(IPT,1),GSCHR(IPT,1),ETHR(IPT,1),
!     +  HFXHR(IPT,1),TLEAFHR(IPT,1),AREA,IHOUR,LGP(IPT),
!     +  PPAR,PPS,PTRANSP,
!     +  THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN,
!     +  DECOUP,DECOUPL)

125          CONTINUE ! End loop over age classes

            ELSE IF ((MODELSS.EQ.2).AND.(FBEAM(IHOUR,1).NE.0.0)) THEN 
! Do calculations separately for sunlit & shaded. Further separate sunlit
! into leaf angle classes.

            DO 135 ISUNLIT = 1,NALPHA+1

              IF (ISUNLIT.GT.NALPHA) THEN
                APAR = DFLUX(IPT,1)*UMOLPERJ
                ANIR = DFLUX(IPT,2)
                FAREA = 1.0 - SUNLA
              ELSE
                APAR = (BFLUX(IPT,1)*BEXTANG(ISUNLIT) + DFLUX(IPT,1))*UMOLPERJ
                ANIR = BFLUX(IPT,2)*BEXTANG(ISUNLIT) + DFLUX(IPT,2)
                FAREA = SUNLA*FALPHA(ISUNLIT)
              END IF

              ATHR = DFLUX(IPT,3)
              RNET = APAR/UMOLPERJ + ANIR + ATHR

              DO 135 IAGE = 1,NOAGEP ! Loop over age classes
                AREA = FAREA * DLI(IAGE,IPT) * VL(IPT) ! m2
                IF (IOHIST.EQ.1) CALL CATEGO(AREA,APAR,HISTO,BINSIZE)

! Call physiology routine
                CALL PSTRANSP(RELDF(IPT),TU(IPT),TD(IPT),RNET, &
       WINDAH(IHOUR)*WINDLAY(LGP(IPT)),APAR,TAIR(IHOUR),CA(IHOUR), &
       RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR), &
       JMAX25(LGP(IPT),IAGE),IECO,EAVJ,EDVJ,DELSJ, &
       VCMAX25(LGP(IPT),IAGE),EAVC,EDVC,DELSC,TVJUP,TVJDN, &
       THETA,AJQ(LGP(IPT),IAGE),RD0(LGP(IPT),IAGE), &
       Q10F,RTEMP,DAYRESP,TBELOW, &
       MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0, &
       GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP, &
       G0,D0L,GAMMA,G1,GK,WLEAF,NSIDES,ITERMAX, &
       GSC,ALEAF,RD,ET,HFX,TLEAF,GBH,DECOUP)

!! MAESHR
!                CALL PSTRANSP(RELDF(IPT),TU(IPT),TD(IPT),RNET,
!     +  WINDAH(IHOUR)*WINDLAY(LGP(IPT)),APAR,TAIR(IHOUR),CA(IHOUR),
!     +  RH(IHOUR),VPD(IHOUR),VMFD(IHOUR),PRESS(IHOUR),SOILMOIST(IHOUR),
!     +  JMAX25(LGP(IPT),IAGE),IECO,EAVJ,EDVJ,DELSJ,
!     +  VCMAX25(LGP(IPT),IAGE),EAVC,EDVC,DELSC,TVJUP,TVJDN,
!     +  THETA,AJQ(LGP(IPT),IAGE),RD0(LGP(IPT),IAGE),
!     &  Q10F,RTEMP,DAYRESP,TBELOW,
!     +  MODELGS,GSREF,GSMIN,PAR0,D0,VK1,VK2,VPD1,VPD2,VMFD0,
!     &  GSJA,GSJB,T0,TREF,TMAX,SMD1,SMD2,SOILDATA,SWPEXP,
!     +  G0,D0L,GAMMA,G1,WLEAF,NSIDES,ITERMAX,
!     +  GSCHR(IPT,ISUNLIT),ALEAFHR(IPT,ISUNLIT),RDHR(IPT,ISUNLIT),
!     +  ETHR(IPT,ISUNLIT),HFXHR(IPT,ISUNLIT),
!     +  TLEAFHR(IPT,ISUNLIT),GBHHR(IPT,ISUNLIT),DECOUP)
!     

! Sum outputs for the hour
              CALL SUMHR(APAR/UMOLPERJ,ANIR,ATHR, &
       ALEAF,RD,GSC,ET,HFX,TLEAF, &
       AREA,IHOUR,LGP(IPT), &
       PPAR,PPS,PTRANSP, &
       THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN, &
       DECOUP,DECOUPL)

!! MAESHR Sum outputs for the hour
!              CALL SUMHR(APAR/UMOLPERJ,ANIR,ATHR,
!     +  ALEAFHR(IPT,ISUNLIT),RDHR(IPT,ISUNLIT),
!     +  GSCHR(IPT,ISUNLIT),ETHR(IPT,ISUNLIT),
!     &  HFXHR(IPT,ISUNLIT),TLEAFHR(IPT,ISUNLIT),
!     +  AREA,IHOUR,LGP(IPT),
!     +  PPAR,PPS,PTRANSP,
!     +  THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN,
!     +  DECOUP,DECOUPL)

135          CONTINUE ! End loop over sunlit / shaded leaves

          END IF ! Separating sunlit & shaded foliage, or not

80        CONTINUE ! End loop over grid points

! Calculate transpiration by applying Penman-Monteith to canopy
          FH2OCAN(IHOUR) = ETCAN(WINDAH(IHOUR),ZHT,Z0HT,ZPD, &
           PRESS(IHOUR),TAIR(IHOUR), &
           THRAB(IHOUR,1)+THRAB(IHOUR,2)+THRAB(IHOUR,3), &
           VPD(IHOUR),GSCAN(IHOUR),STOCKING)
     
! Normalise to get average foliage temperature
        TCAN(IHOUR) = TCAN(IHOUR)/FOLT(1)

! Same for decoupling coefficient:
        DECOUPL(IHOUR) = DECOUPL(IHOUR) / FOLT(1)

        ELSE ! Night-time

! Calculate night-time foliage respiration
          DO 120 IPT = 1,NUMPNT
            DO 120 IAGE = 1,NOAGEP
              AREA = DLI(IAGE,IPT) * VL(IPT)
              RESPF =   AREA * RESP(RD0(LGP(IPT),IAGE),TAIR(IHOUR),Q10F,RTEMP,1.0,TBELOW)
              FCO2(IHOUR) = FCO2(IHOUR) - RESPF
              FRESPF(IHOUR) = FRESPF(IHOUR) + RESPF 
120       CONTINUE

! Canopy T at nighttime is same as air temperature. 
        TCAN(IHOUR) = TAIR(IHOUR)

        END IF ! If day or night

! Calculate non-foliage maintenance respiration (in umol tree-1 s-1)
        FRESPW(IHOUR) = RESP(RMW,TAIR(IHOUR),Q10W,RTEMPW,1.0,TBELOW) * WBIOM
        FRESPB(IHOUR) = RESP(RMB,TAIR(IHOUR),Q10B,RTEMPB,1.0,TBELOW) * BBIOM
        FRESPFR(IHOUR) = RESP(RMFR,TSOIL(IHOUR),Q10R,RTEMPR,1.0,TBELOW) * RBIOM * FRFRAC
        FRESPCR(IHOUR) = RESP(RMCR,TSOIL(IHOUR),Q10R,RTEMPR,1.0,TBELOW) * RBIOM * (1. - FRFRAC)

! MAESHR
! Point-by-point output
! Put in descriptions of each column
!      WRITE (UPT,*) 'COLUMNS:'
!      WRITE (UPT,*) 'PT: point number'
!      WRITE (UPT,*) 'X: x co-ordinate of point (m)'
!      WRITE (UPT,*) 'Y: y co-ordinate of point (m)'
!      WRITE (UPT,*) 'Z: height of point (m)'
!      WRITE (UPT,*) 'VOL: volume assoc. with point (cm3)'
!      WRITE (UPT,*) 'LA: leaf area assoc. with point (cm2)'
!      WRITE (UPT,*) 'SLA: fraction of leaf area which is sunlit'
!      WRITE (UPT,*) 'RBM: absorbed direct-beam PAR (umol m-2 s-1)'
!      WRITE (UPT,*) 'RDF: absorbed sky diffuse PAR (umol m-2 s-1)'
!      WRITE (UPT,*) 'RSC: absorbed scattered PAR (umol m-2 s-1)'
!      WRITE (UPT,*) 'ABM: photosyn of sunlit LA (umol m-2 s-1)'
!      WRITE (UPT,*) 'GBM: stom cond of sunlit LA (mmol m-2 s-1)'
!      WRITE (UPT,*) 'ADF: photosyn of shaded LA (umol m-2 s-1)'
!      WRITE (UPT,*) 'GDF: stom cond of shaded LA (mmol m-2 s-1)'
!      WRITE (UPT,*) 'TBM: leaf temperature of sunlit foliage (oC)'
!      WRITE (UPT,*) 'TDF: leaf temperature of shaded foliage (oC)'
!      WRITE (UPT,*) 'WIND: wind speed at level of grid point (m s-1)'
!      WRITE (UPT,540) 'PT','X','Y','Z','VOL','  LA','  SLA',
!     +  'RBM','RDF','RSC','ABM','GBM','ADF','GDF','TBM','TDF','WIND'
!      DO 130 ILAY = 1,NOLAY
!        WRITE (UPT,*) 'LAYER NO',ILAY
!        DO 130 IPT = 1,NUMPNT
!          IF (LGP(IPT).EQ.ILAY) THEN
!          WRITE (UPT,550) IPT,XL(IPT),YL(IPT),ZL(IPT),
!     +  VL(IPT)*1E6,VL(IPT)*DLT(IPT)*1E4,SUNLAHR(IPT),
!     +  BFLUX(IPT,1)*BEXT*UMOLPERJ,
!     +  (DFLUX(IPT,1)-SCATFX(IPT,1))*UMOLPERJ,
!     +  SCATFX(IPT,1)*UMOLPERJ,
!     +  ALEAFHR(IPT,1),GSCHR(IPT,1)*1E3,
!     +  ALEAFHR(IPT,2),GSCHR(IPT,2)*1E3,
!     +  TLEAFHR(IPT,1),TLEAFHR(IPT,2),WINDAH(IHRNO)*WINDLAY(LGP(IPT))
!          END IF
!130   CONTINUE
!540   FORMAT (A3,A6,19A9)
!550   FORMAT (I3,3(1X,F8.3),1P,2(1X,E10.3),0P,1X,F5.3,14(1X,F8.3))
!
!! Second set of information!
!      WRITE (UPT,*) 
!      WRITE (UPT,*) 'ETBM: transpirn of sun foliage (umol m-2 s-1)'
!      WRITE (UPT,*) 'ETDF: transpirn of shade foliage (umol m-2 s-1)'
!      WRITE (UPT,*) 'RNB: NET RADN of SUNLIT foliage (J m-2 s-1)'
!      WRITE (UPT,*) 'RND: NET RADN of SHADED foliage (J m-2 s-1)'
!      WRITE (UPT,*) 'GBBM: BOUNDARY LAYER COND: SUN (mol m-2 s-1)'
!      WRITE (UPT,*) 'GBDF: BOUNDARY LAYER COND: Shade (mol m-2 s-1)'
!      WRITE (UPT,*) 'RD: LEAF RESPIRATION RATE (Umol m-2 s-1)'
!      WRITE (UPT,*) 'THR: Thermal radiation absorbed (W m-2)'
!    WRITE (UPT,*) 'HFB: Heat flux of sunlit foliage (W m-2)'
!    WRITE (UPT,*) 'HFD: Heat flux of shaded foliage (W m-2)'
!      WRITE (UPT,560) 'PT','ETBM','ETDF','RNB','RND',
!     &    'GBBM','GBDF','RD','THR','HFB','HFD'
!      DO 140 ILAY = 1,NOLAY
!        WRITE (UPT,*) 'LAYER NO',ILAY
!        DO 140 IPT = 1,NUMPNT
!          IF (LGP(IPT).EQ.ILAY) THEN
!          WRITE (UPT,570) IPT,
!     +  ETHR(IPT,1),ETHR(IPT,2),RNETHR(IPT,1),RNETHR(IPT,2),
!     +  GBHHR(IPT,1),GBHHR(IPT,2),RDHR(IPT,1),DFLUX(IPT,3),
!     +  HFXHR(IPT,1),HFXHR(IPT,2)
!          END IF
!140   CONTINUE
!560   FORMAT (A3,10A9)
!570   FORMAT (I3,10(1X,F9.3))

! Output hourly totals
        CALL OUTPUTHR(IOHRLY,IDAY+1,IHOUR,ITREE,ISPEC,TCAN, &
         NOLAY,PPAR,PPS,PTRANSP,FOLLAY, &
         THRAB,FCO2,FRESPF,FRESPW,FRESPB, &
         FH2O,GSCAN,FH2OCAN,FHEAT,DECOUPL)

!**********************************************************************
100   CONTINUE
! End hourly loop

! Calculate daily growth respiration
      TOTRESPWG = GRESP(WBINC,EFFYRW)
      TOTRESPBG = GRESP(BBINC,EFFYRW)
      TOTRESPFRG = GRESP(RBINC*FRFRAC,EFFYRF)
      TOTRESPCRG = GRESP(RBINC*(1.-FRFRAC),EFFYRW)
      TOTRESPFG = GRESP(FBINC,EFFYRF)

! Output daily totals
      CALL SUMDAILY(THRAB,FCO2,FRESPF,FRESPW,FRESPB,FRESPCR,FRESPFR, &
       FH2O,FH2OCAN,FHEAT, &
       TDYAB,TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPB,TOTRESPCR,TOTRESPFR, &
       TOTH2O,TOTH2OCAN,TOTHFX)
      CALL OUTPUTDY(IDAY+1,ITREE,ISPEC,IODAILY,TDYAB,TOTCO2, &
       TOTRESPF,TOTRESPWM,TOTRESPWG, &
       TOTH2O,TOTH2OCAN,TOTHFX, &
       IORESP,TOTRESPCR,TOTRESPFR,TOTRESPFRG,TOTRESPCRG,TOTRESPFG, &
       TOTRESPB,TOTRESPBG)

      IF(ISIMUS.EQ.1)THEN
        CALL OUTPUTUS(IDAY+1,NOUSPOINTS, &
                     XLU,YLU,ZLU,UIBEAM,UIDIFF,PARUS, &
                     APARUS,PSUS,ETUS, &
                     PARUSMEAN,PARUSSD,THRABUS, &
                     FCO2US,FH2OUS,OUTFORMATUS)
      ENDIF

! MAESHR : COMMENT
! Go to next day of simulation
      IDAY = IDAY + NSTEP
      IF ((ISTART+IDAY).LE.IEND) THEN
        CALL SKIPMET(MFLAG,NSTEP)
        GOTO 10
      END IF

!**********************************************************************
110   CONTINUE
! End daily loop

      IF (IOHIST.EQ.1) CALL OUTPUTHIST(UHIST,ITREE,HISTO,BINSIZE)

!**********************************************************************
50    CONTINUE 

! MAESHR
! End loop over trees
!**********************************************************************

! Write diffuse transmittances to file
      REWIND (UTUTD)
      WRITE (UTUTD,1313) (IPT,TU(IPT),TD(IPT),RELDF(IPT),IPT=1,NUMPNT)
1313  FORMAT (1X,I3,5X,F8.4,1X,F8.4,1X,F8.4)


! Write message in Maeserr.dat : simulation was completed.
      CALL SUBERROR('SIMULATION SUCCESSFULLY COMPLETED.',IWARN,0)

      CALL Closef(IODAILY,IOHRLY,IOHIST,IORESP)

      STOP
      END !MAIN
!**********************************************************************


!**********************************************************************
      SUBROUTINE ZEROSTART(HISTO,CANOPYDIMS)
! Set initial values of histogram to zero. 
!**********************************************************************

      USE maestcom
      IMPLICIT NONE
      INTEGER I
      REAL HISTO(MAXHISTO)
      REAL CANOPYDIMS(6)

      DO 10 I = 1,MAXHISTO
        HISTO(I) = 0.0
10    CONTINUE
      DO 20 I = 1,6
        CANOPYDIMS(I) = 0.0
20    CONTINUE
      RETURN
      END !ZeroStart

!**********************************************************************
      SUBROUTINE ZEROD( &
       TDYAB,TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPB, &
       TOTRESPCR,TOTRESPFR,TOTH2O,TOTHFX, &
       TOTH2OCAN)
! This is subroutine to set the initial values of daily total variables
! to zero.
!**********************************************************************

      USE maestcom
      IMPLICIT NONE
      REAL TDYAB(3)
      REAL TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPPB,TOTRESPCR,TOTRESPFR
      REAL TOTH2O,TOTH2OCAN,TOTHFX,CONVERT,TOTRESPB

      TDYAB(1) = 0.0
      TDYAB(2) = 0.0
      TDYAB(3) = 0.0
      TOTCO2 = 0.0
      TOTRESPF = 0.0
      TOTRESPWM = 0.0
      TOTRESPB = 0.0
      TOTRESPFR = 0.0
      TOTRESPCR = 0.0
      TOTH2O = 0.0
      TOTHFX = 0.0
      TOTH2OCAN = 0.0

      RETURN
      END !ZeroD


!**********************************************************************
      SUBROUTINE ZEROHR( &
       THRAB, FCO2, FRESPF, FRESPW, FRESPB, FRESPFR, FRESPCR,  &
       FH2O, GSCAN, FHEAT, PPAR, PPS, PTRANSP, TCAN, DECOUPL, &
       FH2OCAN)
! This is subroutine to set the initial values of hourly total variables
! to zero.
!**********************************************************************

      USE maestcom
      IMPLICIT NONE
      REAL THRAB(MAXHRS,3),TCAN(MAXHRS)
      REAL FCO2(MAXHRS),FRESPF(MAXHRS),FRESPW(MAXHRS),FRESPB(MAXHRS)
      REAL FRESPCR(MAXHRS),FRESPFR(MAXHRS),DECOUPL(MAXHRS)
      REAL GSCAN(MAXHRS),FH2O(MAXHRS),FHEAT(MAXHRS)
      REAL PPAR(MAXLAY,KHRS),PPS(MAXLAY,KHRS),PTRANSP(MAXLAY,KHRS)
      REAL FH2OCAN(MAXHRS)
      FCO2 = 0.0
      FRESPF = 0.0
      FRESPW = 0.0
      FRESPB = 0.0
      FRESPFR = 0.0
      FRESPCR = 0.0
      FH2O = 0.0
      DECOUPL = 0.0
      GSCAN = 0.0
      FHEAT = 0.0
      TCAN = 0.0
      THRAB = 0.0     
      PPAR = 0.0
      PPS = 0.0
      PTRANSP = 0.0
      FH2OCAN = 0.0

      RETURN
      END !ZeroHr

!**********************************************************************
      SUBROUTINE SUMHR(APAR,ANIR,ATHR, &
       ALEAF,RD,GSC,ET,HFX,TLEAF,AREA,IHOUR,ILAY, &
       PPAR,PPS,PTRANSP, &
       THRAB,FCO2,FRESPF,GSCAN,FH2O,FHEAT,TCAN, &
       DECOUP,DECOUPL)
! Sum fluxes from each point to give hourly fluxes.
!**********************************************************************


      USE maestcom
      INTEGER ILAY,IHOUR,NOUSPOINTS
      REAL THRAB(MAXHRS,3),FCO2(MAXHRS),FRESPF(MAXHRS),TCAN(MAXHRS)
      REAL GSCAN(MAXHRS),FH2O(MAXHRS),FHEAT(MAXHRS),DECOUPL(MAXHRS)
      REAL PPAR(MAXLAY,KHRS),PPS(MAXLAY,KHRS),PTRANSP(MAXLAY,KHRS)
      REAL APAR,AREA,ALEAF,ET,ANIR,ATHR,RD,GSC,HFX,TLEADF,DECOUP
      REAL TLEAF

! Sum PAR, photosynthesis, & transpiration by layer
      PPAR(ILAY,IHOUR) = PPAR(ILAY,IHOUR) +  APAR*UMOLPERJ*AREA
      PPS(ILAY,IHOUR) = PPS(ILAY,IHOUR) + ALEAF*AREA
      PTRANSP(ILAY,IHOUR) = PTRANSP(ILAY,IHOUR) + ET*AREA

! Sum all fluxes for the hour
      THRAB(IHOUR,1) = THRAB(IHOUR,1) + APAR*AREA
      THRAB(IHOUR,2) = THRAB(IHOUR,2) + ANIR*AREA
      THRAB(IHOUR,3) = THRAB(IHOUR,3) + ATHR*AREA
      FCO2(IHOUR) = FCO2(IHOUR) + ALEAF*AREA
! Foliage respiration in umol tree-1 s-1
      FRESPF(IHOUR) = FRESPF(IHOUR) + RD*AREA
! Transpiration in umol tree-1 s-1
      FH2O(IHOUR) = FH2O(IHOUR) + ET*AREA
! Stom cond in mol tree-1 s-1
      GSCAN(IHOUR) = GSCAN(IHOUR) + GSC*AREA
! Heat flux in mol tree-1 s-1
      FHEAT(IHOUR) = FHEAT(IHOUR) + HFX*AREA
! Average leaf temperature - will be divided by total leaf area later. 
    TCAN(IHOUR) = TCAN(IHOUR) + TLEAF*AREA
! Average decoupling coefficient - will be divided by total leaf area later. 
      DECOUPL(IHOUR) = DECOUPL(IHOUR) + DECOUP*AREA

      RETURN
      END !SumHR


!**********************************************************************
      SUBROUTINE SUMHRUS(IHOUR,NOUSPOINTS,GRDAREAI,AREAUS,PARUS, &
        PARUSMEAN,PARUSSD,APARUS,PSUS,ETUS,THRABUS, &
        FCO2US,FH2OUS)
     
! Sum fluxes from each understorey point to give hourly fluxes.
! Taken from MAESUS, Feb. '09 (RAD).
!**********************************************************************

      USE maestcom
      IMPLICIT NONE
      INTEGER IHOUR,NOUSPOINTS
      REAL THRABUS(MAXHRS),FCO2US(MAXHRS),FH2OUS(MAXHRS)
      REAL PARUS(MAXHRS,MAXP),APARUS(MAXHRS,MAXP)
      REAL PSUS(MAXHRS,MAXP),ETUS(MAXHRS,MAXP)
      REAL AREAUS(MAXP),PARUSMEAN(MAXHRS),PARUSSD(MAXHRS)
      REAL TESTER(MAXP),GRDAREAI
      REAL, EXTERNAL :: STDEV
      THRABUS(IHOUR) = 0.0
      FCO2US(IHOUR) = 0.0
      FH2OUS(IHOUR) = 0.0

! Average all fluxes across understorey points.
      FCO2US(IHOUR) = SUM(PSUS(IHOUR, 1:NOUSPOINTS)) / &
                REAL(NOUSPOINTS)
      FH2OUS(IHOUR) = SUM(ETUS(IHOUR, 1:NOUSPOINTS)) / &
                REAL(NOUSPOINTS)
      THRABUS(IHOUR) = SUM(APARUS(IHOUR, 1:NOUSPOINTS)) / &
                REAL(NOUSPOINTS)
     
! Average PAR above understorey
      PARUSMEAN(IHOUR) = SUM(PARUS(IHOUR, 1:NOUSPOINTS)) / &
                REAL(NOUSPOINTS)
      PARUSSD(IHOUR) = STDEV(PARUS(IHOUR, 1:NOUSPOINTS),NOUSPOINTS)
    
      RETURN
      END !SUMHRUS

!**********************************************************************
      SUBROUTINE SUMDAILY( &
       THRAB,FCO2,FRESPF,FRESPW,FRESPB,FRESPCR,FRESPFR, &
       FH2O,FH2OCAN,FHEAT, &
       TDYAB,TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPB,TOTRESPCR,TOTRESPFR, &
       TOTH2O,TOTH2OCAN,TOTHFX)
! Sum hourly fluxes to give daily ones
!**********************************************************************

      USE maestcom
      IMPLICIT NONE
      INTEGER IHOUR,J
      REAL THRAB(MAXHRS,3),FCO2(MAXHRS),FRESPF(MAXHRS),FRESPW(MAXHRS)
      REAL FRESPB(MAXHRS),FRESPCR(MAXHRS),FRESPFR(MAXHRS)
      REAL FH2O(MAXHRS),FH2OCAN(MAXHRS),FHEAT(MAXHRS)
      REAL TDYAB(3)
      REAL TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPPB,TOTRESPCR,TOTRESPFR
      REAL TOTH2O,TOTH2OCAN,TOTHFX,CONVERT,TOTRESPB
      REAL, EXTERNAL :: STDEV

      DO 10 IHOUR = 1,KHRS
        TOTCO2 = TOTCO2 + FCO2(IHOUR)
        TOTRESPF = TOTRESPF + FRESPF(IHOUR)
        TOTRESPWM = TOTRESPWM + FRESPW(IHOUR)
        TOTRESPB  = TOTRESPB  + FRESPB(IHOUR)
        TOTRESPCR = TOTRESPCR + FRESPCR(IHOUR)
        TOTRESPFR = TOTRESPFR + FRESPFR(IHOUR)
        TOTH2O = TOTH2O + FH2O(IHOUR)
        TOTH2OCAN = TOTH2OCAN + FH2OCAN(IHOUR)
        TOTHFX = TOTHFX + FHEAT(IHOUR)
        DO 10 J = 1,3
          TDYAB(J) = TDYAB(J) + THRAB(IHOUR,J)
10    CONTINUE

      CONVERT = SPERHR*1E-6

      TOTCO2 = TOTCO2*CONVERT
      TOTRESPF = TOTRESPF*CONVERT
      TOTRESPB = TOTRESPB*CONVERT
      TOTRESPWM = TOTRESPWM*CONVERT
      TOTRESPCR = TOTRESPCR*CONVERT
      TOTRESPFR = TOTRESPFR*CONVERT
      TOTH2O = TOTH2O*CONVERT
      TOTH2OCAN = TOTH2OCAN*CONVERT
      TOTHFX = TOTHFX*CONVERT
      DO 20 J = 1,3
        TDYAB(J) = TDYAB(J)*CONVERT
20    CONTINUE

      RETURN
      END !SumDaily


